//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the AGPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
namespace us.gov
{
    public class protocol
    {
        public static readonly short protocol_suffix = 0;
        public static bool is_node_protocol(short i) { return (i & 3) == protocol_suffix; }

//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__protocol_gov_socket_cs
//------------------generated by apitool- do not edit
// gov_socket - master file: us/apitool/data/gov_socket
    public static readonly short gov_socket_base = 100;
    public static readonly short gov_socket_error = ((gov_socket_base+0)<<2)+protocol_suffix;
    public static readonly short gov_socket_ping = ((gov_socket_base+1)<<2)+protocol_suffix;
    public static readonly short gov_socket_pong = ((gov_socket_base+2)<<2)+protocol_suffix;
//-/----------------generated by apitool- do not edit

//content of file: ../../../api/apitool_generated__protocol_gov_id_cs
//------------------generated by apitool- do not edit
// gov_id - master file: us/apitool/data/gov_id
    public static readonly short gov_id_base = 200;
    public static readonly short gov_id_request = ((gov_id_base+0)<<2)+protocol_suffix;
    public static readonly short gov_id_peer_challenge = ((gov_id_base+1)<<2)+protocol_suffix;
    public static readonly short gov_id_challenge_response = ((gov_id_base+2)<<2)+protocol_suffix;
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit



    }
}
