//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.wallet;
import us.stdint.*;                                                                            // *

public class protocol {

    //#include <us/api/generated/wallet/java/engine/svc>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/wallet/java/engine/svc>
    // engine - master file: us/api/data/wallet/engine

        public static final int engine_begin = 48;
        public static final int engine_print_grid = engine_begin + 0;  // svc 48
        public static final int engine_print_grid_response = engine_begin + 1;  // svc 49

        public static final int engine_print_socket_connections = engine_begin + 2;  // svc 50
        public static final int engine_print_socket_connections_response = engine_begin + 3;  // svc 51

        public static final int engine_allw = engine_begin + 4;  // svc 52
        public static final int engine_allw_response = engine_begin + 5;  // svc 53

        public static final int engine_sync = engine_begin + 6;  // svc 54
        public static final int engine_sync_response = engine_begin + 7;  // svc 55

        public static final int engine_reload_file = engine_begin + 8;  // svc 56
        public static final int engine_reload_file_response = engine_begin + 9;  // svc 57

        public static final int engine_get_component_update = engine_begin + 10;  // svc 58
        public static final int engine_get_component_update_response = engine_begin + 11;  // svc 59

        public static final int engine_get_component_hash = engine_begin + 12;  // svc 60
        public static final int engine_get_component_hash_response = engine_begin + 13;  // svc 61

        public static final int engine_harvest = engine_begin + 14;  // svc 62
        public static final int engine_harvest_response = engine_begin + 15;  // svc 63

        public static final int engine_world = engine_begin + 16;  // svc 64
        public static final int engine_world_response = engine_begin + 17;  // svc 65

        public static final int engine_lookup_wallet = engine_begin + 18;  // svc 66
        public static final int engine_lookup_wallet_response = engine_begin + 19;  // svc 67

        public static final int engine_random_wallet = engine_begin + 20;  // svc 68
        public static final int engine_random_wallet_response = engine_begin + 21;  // svc 69

        public static final int engine_register_w = engine_begin + 22;  // svc 70
        public static final int engine_register_w_response = engine_begin + 23;  // svc 71

        public static final int engine_conf = engine_begin + 24;  // svc 72
        public static final int engine_conf_response = engine_begin + 25;  // svc 73


        public static final int engine_end = 74; // svc 74
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.
    //#include <us/api/generated/wallet/java/pairing/svc>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/wallet/java/pairing/svc>
    // pairing - master file: us/api/data/wallet/pairing

        public static final int pairing_begin = 74;
        public static final int pairing_pair_device = pairing_begin + 0;  // svc 74
        public static final int pairing_pair_device_response = pairing_begin + 1;  // svc 75

        public static final int pairing_unpair_device = pairing_begin + 2;  // svc 76
        public static final int pairing_unpair_device_response = pairing_begin + 3;  // svc 77

        public static final int pairing_list_devices = pairing_begin + 4;  // svc 78
        public static final int pairing_list_devices_response = pairing_begin + 5;  // svc 79

        public static final int pairing_attempts = pairing_begin + 6;  // svc 80
        public static final int pairing_attempts_response = pairing_begin + 7;  // svc 81

        public static final int pairing_prepair_device = pairing_begin + 8;  // svc 82
        public static final int pairing_prepair_device_response = pairing_begin + 9;  // svc 83

        public static final int pairing_unprepair_device = pairing_begin + 10;  // svc 84
        public static final int pairing_unprepair_device_response = pairing_begin + 11;  // svc 85


        public static final int pairing_end = 86; // svc 86
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.
    //#include <us/api/generated/wallet/java/r2r/svc>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/wallet/java/r2r/svc>
    // r2r - master file: us/api/data/wallet/r2r

        public static final int r2r_begin = 86;
        public static final int r2r_trading_msg = r2r_begin + 0;  // svc 86


        public static final int r2r_end = 87; // svc 87
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.
    //#include <us/api/generated/wallet/java/wallet/svc>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/wallet/java/wallet/svc>
    // wallet - master file: us/api/data/wallet/wallet

        public static final int wallet_begin = 87;
        public static final int wallet_balance = wallet_begin + 0;  // svc 87
        public static final int wallet_balance_response = wallet_begin + 1;  // svc 88

        public static final int wallet_list = wallet_begin + 2;  // svc 89
        public static final int wallet_list_response = wallet_begin + 3;  // svc 90

        public static final int wallet_recv_address = wallet_begin + 4;  // svc 91
        public static final int wallet_recv_address_response = wallet_begin + 5;  // svc 92

        public static final int wallet_new_address = wallet_begin + 6;  // svc 93
        public static final int wallet_new_address_response = wallet_begin + 7;  // svc 94

        public static final int wallet_add_address = wallet_begin + 8;  // svc 95
        public static final int wallet_add_address_response = wallet_begin + 9;  // svc 96

        public static final int wallet_transfer = wallet_begin + 10;  // svc 97
        public static final int wallet_transfer_response = wallet_begin + 11;  // svc 98

        public static final int wallet_transfer_from = wallet_begin + 12;  // svc 99
        public static final int wallet_transfer_from_response = wallet_begin + 13;  // svc 100

        public static final int wallet_tx_charge_pay = wallet_begin + 14;  // svc 101
        public static final int wallet_tx_charge_pay_response = wallet_begin + 15;  // svc 102

        public static final int wallet_invoice_verify = wallet_begin + 16;  // svc 103
        public static final int wallet_invoice_verify_response = wallet_begin + 17;  // svc 104

        public static final int wallet_payment_verify = wallet_begin + 18;  // svc 105
        public static final int wallet_payment_verify_response = wallet_begin + 19;  // svc 106

        public static final int wallet_tx_pay = wallet_begin + 20;  // svc 107
        public static final int wallet_tx_pay_response = wallet_begin + 21;  // svc 108

        public static final int wallet_tx_new = wallet_begin + 22;  // svc 109
        public static final int wallet_tx_new_response = wallet_begin + 23;  // svc 110

        public static final int wallet_tx_add_section = wallet_begin + 24;  // svc 111
        public static final int wallet_tx_add_section_response = wallet_begin + 25;  // svc 112

        public static final int wallet_tx_add_input = wallet_begin + 26;  // svc 113
        public static final int wallet_tx_add_input_response = wallet_begin + 27;  // svc 114

        public static final int wallet_tx_add_output = wallet_begin + 28;  // svc 115
        public static final int wallet_tx_add_output_response = wallet_begin + 29;  // svc 116

        public static final int wallet_tx_sign = wallet_begin + 30;  // svc 117
        public static final int wallet_tx_sign_response = wallet_begin + 31;  // svc 118

        public static final int wallet_tx_send = wallet_begin + 32;  // svc 119
        public static final int wallet_tx_send_response = wallet_begin + 33;  // svc 120

        public static final int wallet_tx_decode = wallet_begin + 34;  // svc 121
        public static final int wallet_tx_decode_response = wallet_begin + 35;  // svc 122

        public static final int wallet_tx_check = wallet_begin + 36;  // svc 123
        public static final int wallet_tx_check_response = wallet_begin + 37;  // svc 124

        public static final int wallet_set_supply = wallet_begin + 38;  // svc 125
        public static final int wallet_set_supply_response = wallet_begin + 39;  // svc 126

        public static final int wallet_store_kv = wallet_begin + 40;  // svc 127
        public static final int wallet_store_kv_response = wallet_begin + 41;  // svc 128

        public static final int wallet_rm_kv = wallet_begin + 42;  // svc 129
        public static final int wallet_rm_kv_response = wallet_begin + 43;  // svc 130

        public static final int wallet_store_file = wallet_begin + 44;  // svc 131
        public static final int wallet_store_file_response = wallet_begin + 45;  // svc 132

        public static final int wallet_rm_file = wallet_begin + 46;  // svc 133
        public static final int wallet_rm_file_response = wallet_begin + 47;  // svc 134

        public static final int wallet_search = wallet_begin + 48;  // svc 135
        public static final int wallet_search_response = wallet_begin + 49;  // svc 136

        public static final int wallet_file = wallet_begin + 50;  // svc 137
        public static final int wallet_file_response = wallet_begin + 51;  // svc 138

        public static final int wallet_exec = wallet_begin + 52;  // svc 139

        public static final int wallet_get_subhome = wallet_begin + 53;  // svc 140
        public static final int wallet_get_subhome_response = wallet_begin + 54;  // svc 141

        public static final int wallet_net_info = wallet_begin + 55;  // svc 142
        public static final int wallet_net_info_response = wallet_begin + 56;  // svc 143

        public static final int wallet_compilance_report = wallet_begin + 57;  // svc 144
        public static final int wallet_compilance_report_response = wallet_begin + 58;  // svc 145

        public static final int wallet_priv_key = wallet_begin + 59;  // svc 146
        public static final int wallet_priv_key_response = wallet_begin + 60;  // svc 147

        public static final int wallet_pub_key = wallet_begin + 61;  // svc 148
        public static final int wallet_pub_key_response = wallet_begin + 62;  // svc 149

        public static final int wallet_gen_keys = wallet_begin + 63;  // svc 150
        public static final int wallet_gen_keys_response = wallet_begin + 64;  // svc 151

        public static final int wallet_sign = wallet_begin + 65;  // svc 152
        public static final int wallet_sign_response = wallet_begin + 66;  // svc 153

        public static final int wallet_verify = wallet_begin + 67;  // svc 154
        public static final int wallet_verify_response = wallet_begin + 68;  // svc 155

        public static final int wallet_encrypt = wallet_begin + 69;  // svc 156
        public static final int wallet_encrypt_response = wallet_begin + 70;  // svc 157

        public static final int wallet_decrypt = wallet_begin + 71;  // svc 158
        public static final int wallet_decrypt_response = wallet_begin + 72;  // svc 159

        public static final int wallet_patch_os = wallet_begin + 73;  // svc 160
        public static final int wallet_patch_os_response = wallet_begin + 74;  // svc 161

        public static final int wallet_list_protocols = wallet_begin + 75;  // svc 162
        public static final int wallet_list_protocols_response = wallet_begin + 76;  // svc 163

        public static final int wallet_trade = wallet_begin + 77;  // svc 164
        public static final int wallet_trade_response = wallet_begin + 78;  // svc 165

        public static final int wallet_list_trades = wallet_begin + 79;  // svc 166
        public static final int wallet_list_trades_response = wallet_begin + 80;  // svc 167

        public static final int wallet_kill_trade = wallet_begin + 81;  // svc 168
        public static final int wallet_kill_trade_response = wallet_begin + 82;  // svc 169

        public static final int wallet_exec_trade = wallet_begin + 83;  // svc 170

        public static final int wallet_qr = wallet_begin + 84;  // svc 171
        public static final int wallet_qr_response = wallet_begin + 85;  // svc 172

        public static final int wallet_bookmark_add = wallet_begin + 86;  // svc 173
        public static final int wallet_bookmark_add_response = wallet_begin + 87;  // svc 174

        public static final int wallet_bookmark_delete = wallet_begin + 88;  // svc 175
        public static final int wallet_bookmark_delete_response = wallet_begin + 89;  // svc 176

        public static final int wallet_bookmark_list = wallet_begin + 90;  // svc 177
        public static final int wallet_bookmark_list_response = wallet_begin + 91;  // svc 178

        public static final int wallet_timeseries_list = wallet_begin + 92;  // svc 179
        public static final int wallet_timeseries_list_response = wallet_begin + 93;  // svc 180

        public static final int wallet_timeseries_show = wallet_begin + 94;  // svc 181
        public static final int wallet_timeseries_show_response = wallet_begin + 95;  // svc 182

        public static final int wallet_timeseries_new = wallet_begin + 96;  // svc 183
        public static final int wallet_timeseries_new_response = wallet_begin + 97;  // svc 184

        public static final int wallet_timeseries_add = wallet_begin + 98;  // svc 185
        public static final int wallet_timeseries_add_response = wallet_begin + 99;  // svc 186


        public static final int wallet_end = 187; // svc 187
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.

}

