//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.gov.id;
import static us.gov.socket.types.*;                                                           // *
import us.ko;                                                                                  // ko
import us.gov.crypto.sha256;                                                                   // sha256
import us.string;                                                                              // string

public interface caller_api extends dto {

    //#include <us/api/generated/java/gov/id/cllr_purevir>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/java/gov/id/cllr_purevir>
    // id - master file: us/api/data/gov/id

      ko call_request(final sha256.hash_t msg);
      ko call_peer_challenge(final peer_challenge_in_t o_in);
      ko call_challenge_response(final challenge_response_in_t o_in);
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.

}
