//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the AGPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.gov.socket;
import us.ko;                                                                                  // ko
import us.string;                                                                              // string

public interface api extends caller_api {

    //#include <us/api/generated/java/gov/socket/hdlr_purevir>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/java/gov/socket/hdlr_purevir>
    // socket - master file: us/api/data/gov/socket

      ko handle_error(final datagram dgram, final string msg);
      ko handle_ping(final string msg, string ans);
      ko handle_finished(final string reason);
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.

}

