//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us;
import java.io.PrintStream;                                                                    // PrintStream

public class vcs {

//#include <us/vcs_git_java>
//------------------------------------------------------------__begin__------generated by configure, do not edit.
//content of file: <us/vcs_git_java>
public static final String src = "https://github.com/user/project";
public static final String devjob = "";
public static final String devjobtag = "";
public static final String brand = "us";
public static final String branch = "alpha-43";
public static final String codehash = "f9df30d1b27ce4814942d78cc343dc75f4743927+";
public static final String cfghash = "e49747b55b0b893e2ada612ae396c48b1fd48e8e97a37dab0f3067b0a7ffa14f";
public static final String hashname = "f9df30+.e49747";
public static final String version_name = "us-alpha-43_f9df30+.e49747";
public static final String build_date = "2022-10-08_08-24-08";
//-/----------------------------------------------------------___end___------generated by configure, do not edit.

    public static String apkfilename() {
        return brand + "-wallet_android_" + branch + '_' + hashname + ".apk";
    }

    public static String sdk_name() {
         return brand + "-wallet-sdk_java_" + branch;
    }

    public static void version(PrintStream os) {
        os.print(version_name + ' ' + codehash + ' ' + build_date);
    }

    public static String version() {
        return version_name + ' ' + codehash + ' ' + build_date;
    }

    public static String name_date() {
        return version_name + ' ' + build_date;
    }
}

