//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us;
import java.io.PrintStream;                                                                    // PrintStream

public class vcs {

//#include <us/vcs_git_java>
//------------------------------------------------------------__begin__------generated by configure, do not edit.
//content of file: <us/vcs_git_java>
public static final String src = "https://github.com/user/project";
public static final String devjob = "";
public static final String devjobtag = "";
public static final String brand = "us";
public static final String branch = "alpha-54";
public static final String codehash = "9ca859d4839190e8bf52a44378d21d2ac3fbe2e7+";
public static final String cfghash = "bb70debe5a5eb618ee62e5aa16b2467b2a71d9c796d07b37e50d042d3bf7c0b7";
public static final String hashname = "9ca859+.bb70de";
public static final String version_name = "us-alpha-54_9ca859+.bb70de";
public static final String build_date = "2022-12-16_21-13-35";
//-/----------------------------------------------------------___end___------generated by configure, do not edit.

    public static String apkfilename() {
        return brand + "-wallet_android_" + branch + '_' + hashname + ".apk";
    }

    public static String sdk_name() {
         return brand + "-wallet-sdk_java_" + branch;
    }

    public static void version(PrintStream os) {
        os.print(version_name + ' ' + codehash + ' ' + build_date);
    }

    public static String version() {
        return version_name + ' ' + codehash + ' ' + build_date;
    }

    public static String name_date() {
        return version_name + ' ' + build_date;
    }
}

