//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the AGPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
using System.IO;

namespace us.wallet
{
    interface daemon_api : wallet_api, pairing_api, sys_api
    {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_wallet_daemon_cs_purevir
//------------------generated by apitool- do not edit
// wallet_daemon - master file: us/apitool/data/wallet_daemon
  void list_protocols(Stream os);
  void trade(string arg0, string arg1, string arg2, Stream os);
  void list_trades(Stream os);
  void kill_trade(byte[] arg0, Stream os);
  void command_trade(byte[] arg0, string arg1, Stream os);
  void command_trade_bin(byte[] arg0, string arg1, Stream os);
  void grid(Stream os);
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit
    }
}
