//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the AGPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
namespace us.wallet
{
    class protocol
    {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__protocol_wallet-daemon_cs
//------------------generated by apitool- do not edit
// wallet - master file: us/apitool/data/wallet
    public static readonly short wallet_base = 100;
    public static readonly short wallet_ping = wallet_base+0;
    public static readonly short wallet_balance = wallet_base+2;
    public static readonly short wallet_list = wallet_base+4;
    public static readonly short wallet_new_address = wallet_base+6;
    public static readonly short wallet_add_address = wallet_base+8;
    public static readonly short wallet_transfer = wallet_base+10;
    public static readonly short wallet_transfer_from = wallet_base+12;
    public static readonly short wallet_tx_charge_pay = wallet_base+14;
    public static readonly short wallet_tx_pay = wallet_base+16;
    public static readonly short wallet_tx_new = wallet_base+18;
    public static readonly short wallet_tx_add_section = wallet_base+20;
    public static readonly short wallet_tx_add_input = wallet_base+22;
    public static readonly short wallet_tx_add_output = wallet_base+24;
    public static readonly short wallet_tx_make_p2pkh = wallet_base+26;
    public static readonly short wallet_tx_sign = wallet_base+28;
    public static readonly short wallet_tx_send = wallet_base+30;
    public static readonly short wallet_tx_decode = wallet_base+32;
    public static readonly short wallet_tx_check = wallet_base+34;
    public static readonly short wallet_set_supply = wallet_base+36;
    public static readonly short wallet_store_kv = wallet_base+38;
    public static readonly short wallet_rm_kv = wallet_base+40;
    public static readonly short wallet_store_file = wallet_base+42;
    public static readonly short wallet_rm_file = wallet_base+44;
    public static readonly short wallet_search = wallet_base+46;
    public static readonly short wallet_file = wallet_base+48;
// pairing - master file: us/apitool/data/pairing
    public static readonly short pairing_base = 200;
    public static readonly short pairing_pair = pairing_base+0;
    public static readonly short pairing_unpair = pairing_base+2;
    public static readonly short pairing_list_devices = pairing_base+4;
// sys - master file: us/apitool/data/sys
    public static readonly short sys_base = 300;
//-/----------------generated by apitool- do not edit

//content of file: ../../../api/apitool_generated__protocol_wallet_daemon_cs
//------------------generated by apitool- do not edit
// wallet_daemon - master file: us/apitool/data/wallet_daemon
    public static readonly short wallet_daemon_base = 0;
    public static readonly short wallet_daemon_list_protocols = wallet_daemon_base+0;
    public static readonly short wallet_daemon_trade = wallet_daemon_base+2;
    public static readonly short wallet_daemon_list_trades = wallet_daemon_base+4;
    public static readonly short wallet_daemon_kill_trade = wallet_daemon_base+6;
    public static readonly short wallet_daemon_command_trade = wallet_daemon_base+8;
    public static readonly short wallet_daemon_command_trade_bin = wallet_daemon_base+10;
    public static readonly short wallet_daemon_grid = wallet_daemon_base+12;
//-/----------------generated by apitool- do not edit

        //-/-------------------------------------------------------------------generated by make, do not edit

        public static readonly short trading_base = 1000;
        public static readonly short trading_msg = (short)(trading_base + 0);
    }
}
