//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the AGPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
namespace us.wallet
{
    class sys_rpc_api : sys_api
    {
        public sys_rpc_api(rpc_api endpoint_)
        {
            endpoint = endpoint_;
        }

//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_sys_cs_rpc-impl
//------------------generated by apitool- do not edit
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

        rpc_api endpoint;
    }
}
