//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.gov.engine;
import static us.gov.crypto.ripemd160.hash_t;                                                  // hash_t
import static us.gov.io.types.*;                                                               // *
import static us.gov.socket.types.*;                                                           // *
import static us.ko.*;                                                                         // *
import us.ko;                                                                                  // ko
import us.gov.protocol;                                                                        // protocol
import us.gov.crypto.sha256;                                                                   // sha256
import us.string;                                                                              // string

public interface caller_api extends dto {

    //OFF#include <us/api/generated/java/gov/engine/cllr_purevir>
    //OFF#include <us/api/generated/java/gov/engine_auth/cllr_purevir>
    //OFF#include <us/api/generated/java/gov/cash/cllr_purevir>
    //#include <us/api/generated/java/gov/traders/cllr_purevir>
    //------------------------------------------------------------__begin__------generated by configure, do not edit.
    //content of file: <us/api/generated/java/gov/traders/cllr_purevir>
    // traders - master file: us/api/data/gov/traders

      ko call_wallets(vector_hash wallets);
      ko call_lookup_wallet(final hash_t pkh, lookup_wallet_out_dst_t o_out);
      ko call_random_wallet(random_wallet_out_dst_t o_out);
    //-/----------------------------------------------------------___end___------generated by configure, do not edit.
    //OFF#include <us/api/generated/java/gov/sys/cllr_purevir>

}

