//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.gov.engine;
import us.CFG;                                                                                 // CFG
import static java.util.Map.entry;                                                             // entry
import java.util.HashMap;                                                                      // HashMap
import static us.gov.socket.types.*;                                                           // *
import java.util.Map;                                                                          // Map

public class svcfish_t {

    static void log(final String line) {                        //--strip
        CFG.log_gov("svcfish_t: " + line);                      //--strip
    }                                                           //--strip

    public svcfish_t() {
        {
            HashMap<Integer, Integer> db = db01;
            //#include <us/api/generated/gov/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_from_prev_v>
            // / socket_error (1) -> socket_error (1) Same function
            // / socket_ping (2) -> socket_ping (2) Same function
            // / socket_ping_response (3) -> socket_ping_response (3) Same function
            // / socket_finished (4) -> socket_finished (4) Same function
            // / id_request (5) -> id_request (5) Same function
            // / id_peer_challenge (6) -> id_peer_challenge (6) Same function
            db.put(Integer.valueOf(8), Integer.valueOf(7)); // ! id_challenge2_response (8) -> id_challenge2_response (7) svc changed
            db.put(Integer.valueOf(9), Integer.valueOf(8)); // ! id_verification_result (9) -> id_verification_result (8) svc changed
            db.put(Integer.valueOf(10), Integer.valueOf(9)); // ! auth_f1 (10) -> auth_f1 (9) svc changed
            db.put(Integer.valueOf(11), Integer.valueOf(10)); // ! peer_f1 (11) -> peer_f1 (10) svc changed
            db.put(Integer.valueOf(12), Integer.valueOf(11)); // ! relay_push (12) -> relay_push (11) svc changed
            db.put(Integer.valueOf(13), Integer.valueOf(12)); // ! dfs_file_request (13) -> dfs_file_request (12) svc changed
            db.put(Integer.valueOf(14), Integer.valueOf(13)); // ! dfs_file_request_ret (14) -> dfs_file_request_ret (13) svc changed
            db.put(Integer.valueOf(15), Integer.valueOf(14)); // ! engine_local_deltas (15) -> engine_local_deltas (14) svc changed
            db.put(Integer.valueOf(16), Integer.valueOf(15)); // ! engine_vote_tip (16) -> engine_vote_tip (15) svc changed
            db.put(Integer.valueOf(17), Integer.valueOf(16)); // ! engine_query_block (17) -> engine_query_block (16) svc changed
            db.put(Integer.valueOf(18), Integer.valueOf(17)); // ! engine_query_block_ret (18) -> engine_query_block_ret (17) svc changed
            db.put(Integer.valueOf(19), Integer.valueOf(18)); // ! engine_sysop (19) -> engine_sysop (18) svc changed
            db.put(Integer.valueOf(20), Integer.valueOf(19)); // ! engine_sysop_ret (20) -> engine_sysop_ret (19) svc changed
            db.put(Integer.valueOf(21), Integer.valueOf(20)); // ! engine_track (21) -> engine_track (20) svc changed
            db.put(Integer.valueOf(22), Integer.valueOf(21)); // ! engine_track_ret (22) -> engine_track_ret (21) svc changed
            db.put(Integer.valueOf(23), Integer.valueOf(22)); // ! engine_ev (23) -> engine_ev (22) svc changed
            db.put(Integer.valueOf(24), Integer.valueOf(23)); // ! engine_ev_track (24) -> engine_ev_track (23) svc changed
            db.put(Integer.valueOf(25), Integer.valueOf(24)); // ! engine_ev_track_ret (25) -> engine_ev_track_ret (24) svc changed
            db.put(Integer.valueOf(26), Integer.valueOf(25)); // ! engine_harvest (26) -> engine_harvest (25) svc changed
            db.put(Integer.valueOf(27), Integer.valueOf(26)); // ! engine_harvest_rollback (27) -> engine_harvest_rollback (26) svc changed
            db.put(Integer.valueOf(28), Integer.valueOf(27)); // ! cash_fetch_accounts (28) -> cash_fetch_accounts (27) svc changed
            db.put(Integer.valueOf(29), Integer.valueOf(28)); // ! cash_fetch_accounts_ret (29) -> cash_fetch_accounts_ret (28) svc changed
            db.put(Integer.valueOf(30), Integer.valueOf(29)); // ! cash_share_file (30) -> cash_share_file (29) svc changed
            db.put(Integer.valueOf(31), Integer.valueOf(30)); // ! cash_share_file_ret (31) -> cash_share_file_ret (30) svc changed
            db.put(Integer.valueOf(32), Integer.valueOf(31)); // ! cash_search_kv (32) -> cash_search_kv (31) svc changed
            db.put(Integer.valueOf(33), Integer.valueOf(32)); // ! cash_search_kv_ret (33) -> cash_search_kv_ret (32) svc changed
            db.put(Integer.valueOf(34), Integer.valueOf(33)); // ! cash_file_hash (34) -> cash_file_hash (33) svc changed
            db.put(Integer.valueOf(35), Integer.valueOf(34)); // ! cash_file_hash_ret (35) -> cash_file_hash_ret (34) svc changed
            db.put(Integer.valueOf(36), Integer.valueOf(35)); // ! cash_file_content (36) -> cash_file_content (35) svc changed
            db.put(Integer.valueOf(37), Integer.valueOf(36)); // ! cash_file_content_ret (37) -> cash_file_content_ret (36) svc changed
            db.put(Integer.valueOf(38), Integer.valueOf(37)); // ! engine_auth_nodes (38) -> engine_auth_nodes (37) svc changed
            db.put(Integer.valueOf(39), Integer.valueOf(38)); // ! engine_auth_nodes_ret (39) -> engine_auth_nodes_ret (38) svc changed
            db.put(Integer.valueOf(40), Integer.valueOf(39)); // ! engine_auth_lookup_node (40) -> engine_auth_lookup_node (39) svc changed
            db.put(Integer.valueOf(41), Integer.valueOf(40)); // ! engine_auth_lookup_node_ret (41) -> engine_auth_lookup_node_ret (40) svc changed
            db.put(Integer.valueOf(42), Integer.valueOf(41)); // ! traders_wallets (42) -> traders_wallets (41) svc changed
            db.put(Integer.valueOf(43), Integer.valueOf(42)); // ! traders_wallets_ret (43) -> traders_wallets_ret (42) svc changed
            db.put(Integer.valueOf(44), Integer.valueOf(43)); // ! traders_lookup_wallet (44) -> traders_lookup_wallet (43) svc changed
            db.put(Integer.valueOf(45), Integer.valueOf(44)); // ! traders_lookup_wallet_ret (45) -> traders_lookup_wallet_ret (44) svc changed
            db.put(Integer.valueOf(46), Integer.valueOf(45)); // ! traders_random_wallet (46) -> traders_random_wallet (45) svc changed
            db.put(Integer.valueOf(47), Integer.valueOf(46)); // ! traders_random_wallet_ret (47) -> traders_random_wallet_ret (46) svc changed
            db.put(Integer.valueOf(48), Integer.valueOf(47)); // ! sys_f1 (48) -> sys_f1 (47) svc changed
            db.put(Integer.valueOf(7), Integer.valueOf(-1)); // - id_challenge_response (7) ->  (-1) svc deleted
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
        {
            HashMap<Integer, Integer> db = db10;
            //#include <us/api/generated/gov/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_to_prev_v>
            // / socket_error (1) -> socket_error (1) Same function
            // / socket_ping (2) -> socket_ping (2) Same function
            // / socket_ping_response (3) -> socket_ping_response (3) Same function
            // / socket_finished (4) -> socket_finished (4) Same function
            // / id_request (5) -> id_request (5) Same function
            // / id_peer_challenge (6) -> id_peer_challenge (6) Same function
            db.put(Integer.valueOf(7), Integer.valueOf(8)); // ! id_challenge2_response (7) -> id_challenge2_response (8) svc changed
            db.put(Integer.valueOf(8), Integer.valueOf(9)); // ! id_verification_result (8) -> id_verification_result (9) svc changed
            db.put(Integer.valueOf(9), Integer.valueOf(10)); // ! auth_f1 (9) -> auth_f1 (10) svc changed
            db.put(Integer.valueOf(10), Integer.valueOf(11)); // ! peer_f1 (10) -> peer_f1 (11) svc changed
            db.put(Integer.valueOf(11), Integer.valueOf(12)); // ! relay_push (11) -> relay_push (12) svc changed
            db.put(Integer.valueOf(12), Integer.valueOf(13)); // ! dfs_file_request (12) -> dfs_file_request (13) svc changed
            db.put(Integer.valueOf(13), Integer.valueOf(14)); // ! dfs_file_request_ret (13) -> dfs_file_request_ret (14) svc changed
            db.put(Integer.valueOf(14), Integer.valueOf(15)); // ! engine_local_deltas (14) -> engine_local_deltas (15) svc changed
            db.put(Integer.valueOf(15), Integer.valueOf(16)); // ! engine_vote_tip (15) -> engine_vote_tip (16) svc changed
            db.put(Integer.valueOf(16), Integer.valueOf(17)); // ! engine_query_block (16) -> engine_query_block (17) svc changed
            db.put(Integer.valueOf(17), Integer.valueOf(18)); // ! engine_query_block_ret (17) -> engine_query_block_ret (18) svc changed
            db.put(Integer.valueOf(18), Integer.valueOf(19)); // ! engine_sysop (18) -> engine_sysop (19) svc changed
            db.put(Integer.valueOf(19), Integer.valueOf(20)); // ! engine_sysop_ret (19) -> engine_sysop_ret (20) svc changed
            db.put(Integer.valueOf(20), Integer.valueOf(21)); // ! engine_track (20) -> engine_track (21) svc changed
            db.put(Integer.valueOf(21), Integer.valueOf(22)); // ! engine_track_ret (21) -> engine_track_ret (22) svc changed
            db.put(Integer.valueOf(22), Integer.valueOf(23)); // ! engine_ev (22) -> engine_ev (23) svc changed
            db.put(Integer.valueOf(23), Integer.valueOf(24)); // ! engine_ev_track (23) -> engine_ev_track (24) svc changed
            db.put(Integer.valueOf(24), Integer.valueOf(25)); // ! engine_ev_track_ret (24) -> engine_ev_track_ret (25) svc changed
            db.put(Integer.valueOf(25), Integer.valueOf(26)); // ! engine_harvest (25) -> engine_harvest (26) svc changed
            db.put(Integer.valueOf(26), Integer.valueOf(27)); // ! engine_harvest_rollback (26) -> engine_harvest_rollback (27) svc changed
            db.put(Integer.valueOf(27), Integer.valueOf(28)); // ! cash_fetch_accounts (27) -> cash_fetch_accounts (28) svc changed
            db.put(Integer.valueOf(28), Integer.valueOf(29)); // ! cash_fetch_accounts_ret (28) -> cash_fetch_accounts_ret (29) svc changed
            db.put(Integer.valueOf(29), Integer.valueOf(30)); // ! cash_share_file (29) -> cash_share_file (30) svc changed
            db.put(Integer.valueOf(30), Integer.valueOf(31)); // ! cash_share_file_ret (30) -> cash_share_file_ret (31) svc changed
            db.put(Integer.valueOf(31), Integer.valueOf(32)); // ! cash_search_kv (31) -> cash_search_kv (32) svc changed
            db.put(Integer.valueOf(32), Integer.valueOf(33)); // ! cash_search_kv_ret (32) -> cash_search_kv_ret (33) svc changed
            db.put(Integer.valueOf(33), Integer.valueOf(34)); // ! cash_file_hash (33) -> cash_file_hash (34) svc changed
            db.put(Integer.valueOf(34), Integer.valueOf(35)); // ! cash_file_hash_ret (34) -> cash_file_hash_ret (35) svc changed
            db.put(Integer.valueOf(35), Integer.valueOf(36)); // ! cash_file_content (35) -> cash_file_content (36) svc changed
            db.put(Integer.valueOf(36), Integer.valueOf(37)); // ! cash_file_content_ret (36) -> cash_file_content_ret (37) svc changed
            db.put(Integer.valueOf(37), Integer.valueOf(38)); // ! engine_auth_nodes (37) -> engine_auth_nodes (38) svc changed
            db.put(Integer.valueOf(38), Integer.valueOf(39)); // ! engine_auth_nodes_ret (38) -> engine_auth_nodes_ret (39) svc changed
            db.put(Integer.valueOf(39), Integer.valueOf(40)); // ! engine_auth_lookup_node (39) -> engine_auth_lookup_node (40) svc changed
            db.put(Integer.valueOf(40), Integer.valueOf(41)); // ! engine_auth_lookup_node_ret (40) -> engine_auth_lookup_node_ret (41) svc changed
            db.put(Integer.valueOf(41), Integer.valueOf(42)); // ! traders_wallets (41) -> traders_wallets (42) svc changed
            db.put(Integer.valueOf(42), Integer.valueOf(43)); // ! traders_wallets_ret (42) -> traders_wallets_ret (43) svc changed
            db.put(Integer.valueOf(43), Integer.valueOf(44)); // ! traders_lookup_wallet (43) -> traders_lookup_wallet (44) svc changed
            db.put(Integer.valueOf(44), Integer.valueOf(45)); // ! traders_lookup_wallet_ret (44) -> traders_lookup_wallet_ret (45) svc changed
            db.put(Integer.valueOf(45), Integer.valueOf(46)); // ! traders_random_wallet (45) -> traders_random_wallet (46) svc changed
            db.put(Integer.valueOf(46), Integer.valueOf(47)); // ! traders_random_wallet_ret (46) -> traders_random_wallet_ret (47) svc changed
            db.put(Integer.valueOf(47), Integer.valueOf(48)); // ! sys_f1 (47) -> sys_f1 (48) svc changed
            // /  (-1) -> id_challenge_response (7) wont be called
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
    }

    public void from_prev(svc_t svc) {
        Integer i = db01.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    public void to_prev(svc_t svc) {
        Integer i = db10.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    HashMap<Integer, Integer> db01 = new HashMap<Integer, Integer>();
    HashMap<Integer, Integer> db10 = new HashMap<Integer, Integer>();

}

