//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.gov.engine;
import static us.gov.socket.types.*;                                                           // *
import java.util.HashMap;
import java.util.Map;
import static java.util.Map.entry;
import us.CFG;

public class svcfish_t {

    static void log(final String line) {                        //--strip
        CFG.log_gov("svcfish_t: " + line);                      //--strip
    }                                                           //--strip

    public svcfish_t() {
        {
            HashMap<Integer, Integer> db = db01;
            //#include <us/api/generated/gov/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_from_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
        {
            HashMap<Integer, Integer> db = db10;
            //#include <us/api/generated/gov/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_to_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
    }

    public void from_prev(svc_t svc) {
        Integer i = db01.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    public void to_prev(svc_t svc) {
        Integer i = db10.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    HashMap<Integer, Integer> db01 = new HashMap<Integer, Integer>();
    HashMap<Integer, Integer> db10 = new HashMap<Integer, Integer>();

}

