//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.wallet.engine;
import us.CFG;                                                                                 // CFG
import static java.util.Map.entry;                                                             // entry
import java.util.HashMap;                                                                      // HashMap
import static us.gov.socket.types.*;                                                           // *
import java.util.Map;                                                                          // Map

public class svcfish_t {

    static void log(final String line) {                        //--strip
        CFG.log_gov("svcfish_t: " + line);                      //--strip
    }                                                           //--strip

    public svcfish_t() {
        {
            HashMap<Integer, Integer> db = db01;
            //#include <us/api/generated/gov/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_from_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_from_prev_v>
            // / engine_print_grid (48) -> engine_print_grid (48) Same function
            // / engine_print_grid_response (49) -> engine_print_grid_response (49) Same function
            // / engine_print_socket_connections (50) -> engine_print_socket_connections (50) Same function
            // / engine_print_socket_connections_response (51) -> engine_print_socket_connections_response (51) Same function
            // / engine_allw (52) -> engine_allw (52) Same function
            // / engine_allw_response (53) -> engine_allw_response (53) Same function
            // / engine_sync (54) -> engine_sync (54) Same function
            // / engine_sync_response (55) -> engine_sync_response (55) Same function
            // / engine_reload_file (56) -> engine_reload_file (56) Same function
            // / engine_reload_file_response (57) -> engine_reload_file_response (57) Same function
            // / engine_get_component_update (58) -> engine_get_component_update (58) Same function
            // / engine_get_component_update_response (59) -> engine_get_component_update_response (59) Same function
            // / engine_get_component_hash (60) -> engine_get_component_hash (60) Same function
            // / engine_get_component_hash_response (61) -> engine_get_component_hash_response (61) Same function
            // / engine_harvest (62) -> engine_harvest (62) Same function
            // / engine_harvest_response (63) -> engine_harvest_response (63) Same function
            // / engine_world (64) -> engine_world (64) Same function
            // / engine_world_response (65) -> engine_world_response (65) Same function
            // / engine_lookup_wallet (66) -> engine_lookup_wallet (66) Same function
            // / engine_lookup_wallet_response (67) -> engine_lookup_wallet_response (67) Same function
            // / engine_random_wallet (68) -> engine_random_wallet (68) Same function
            // / engine_random_wallet_response (69) -> engine_random_wallet_response (69) Same function
            // / engine_register_w (70) -> engine_register_w (70) Same function
            // / engine_register_w_response (71) -> engine_register_w_response (71) Same function
            // / engine_conf (72) -> engine_conf (72) Same function
            // / engine_conf_response (73) -> engine_conf_response (73) Same function
            // /  (-1) -> engine_r2r_all_index_hdr (74) New function
            // /  (-1) -> engine_r2r_all_index_hdr_response (75) New function
            // /  (-1) -> engine_r2r_all_bookmarks (76) New function
            // /  (-1) -> engine_r2r_all_bookmarks_response (77) New function
            // /  (-1) -> engine_r2r_all_index (78) New function
            // /  (-1) -> engine_r2r_all_index_response (79) New function
            db.put(Integer.valueOf(74), Integer.valueOf(80)); // ! pairing_pair_device (74) -> pairing_pair_device (80) svc changed
            db.put(Integer.valueOf(75), Integer.valueOf(81)); // ! pairing_pair_device_ret (75) -> pairing_pair_device_ret (81) svc changed
            db.put(Integer.valueOf(76), Integer.valueOf(82)); // ! pairing_unpair_device (76) -> pairing_unpair_device (82) svc changed
            db.put(Integer.valueOf(77), Integer.valueOf(83)); // ! pairing_unpair_device_ret (77) -> pairing_unpair_device_ret (83) svc changed
            db.put(Integer.valueOf(78), Integer.valueOf(84)); // ! pairing_list_devices (78) -> pairing_list_devices (84) svc changed
            db.put(Integer.valueOf(79), Integer.valueOf(85)); // ! pairing_list_devices_ret (79) -> pairing_list_devices_ret (85) svc changed
            db.put(Integer.valueOf(80), Integer.valueOf(86)); // ! pairing_attempts (80) -> pairing_attempts (86) svc changed
            db.put(Integer.valueOf(81), Integer.valueOf(87)); // ! pairing_attempts_ret (81) -> pairing_attempts_ret (87) svc changed
            db.put(Integer.valueOf(82), Integer.valueOf(88)); // ! pairing_prepair_device (82) -> pairing_prepair_device (88) svc changed
            db.put(Integer.valueOf(83), Integer.valueOf(89)); // ! pairing_prepair_device_ret (83) -> pairing_prepair_device_ret (89) svc changed
            db.put(Integer.valueOf(84), Integer.valueOf(90)); // ! pairing_unprepair_device (84) -> pairing_unprepair_device (90) svc changed
            db.put(Integer.valueOf(85), Integer.valueOf(91)); // ! pairing_unprepair_device_ret (85) -> pairing_unprepair_device_ret (91) svc changed
            db.put(Integer.valueOf(86), Integer.valueOf(92)); // ! r2r_trading_msg (86) -> r2r_trading_msg (92) svc changed
            // /  (-1) -> r2r_trading_msg2 (93) New function
            db.put(Integer.valueOf(87), Integer.valueOf(94)); // ! wallet_balance (87) -> wallet_balance (94) svc changed
            db.put(Integer.valueOf(88), Integer.valueOf(95)); // ! wallet_balance_ret (88) -> wallet_balance_ret (95) svc changed
            db.put(Integer.valueOf(89), Integer.valueOf(96)); // ! wallet_list (89) -> wallet_list (96) svc changed
            db.put(Integer.valueOf(90), Integer.valueOf(97)); // ! wallet_list_ret (90) -> wallet_list_ret (97) svc changed
            db.put(Integer.valueOf(91), Integer.valueOf(98)); // ! wallet_recv_address (91) -> wallet_recv_address (98) svc changed
            db.put(Integer.valueOf(92), Integer.valueOf(99)); // ! wallet_recv_address_ret (92) -> wallet_recv_address_ret (99) svc changed
            db.put(Integer.valueOf(93), Integer.valueOf(100)); // ! wallet_new_address (93) -> wallet_new_address (100) svc changed
            db.put(Integer.valueOf(94), Integer.valueOf(101)); // ! wallet_new_address_ret (94) -> wallet_new_address_ret (101) svc changed
            db.put(Integer.valueOf(95), Integer.valueOf(102)); // ! wallet_add_address (95) -> wallet_add_address (102) svc changed
            db.put(Integer.valueOf(96), Integer.valueOf(103)); // ! wallet_add_address_ret (96) -> wallet_add_address_ret (103) svc changed
            db.put(Integer.valueOf(97), Integer.valueOf(104)); // ! wallet_transfer (97) -> wallet_transfer (104) svc changed
            db.put(Integer.valueOf(98), Integer.valueOf(105)); // ! wallet_transfer_ret (98) -> wallet_transfer_ret (105) svc changed
            db.put(Integer.valueOf(99), Integer.valueOf(106)); // ! wallet_transfer_from (99) -> wallet_transfer_from (106) svc changed
            db.put(Integer.valueOf(100), Integer.valueOf(107)); // ! wallet_transfer_from_ret (100) -> wallet_transfer_from_ret (107) svc changed
            db.put(Integer.valueOf(101), Integer.valueOf(108)); // ! wallet_tx_charge_pay (101) -> wallet_tx_charge_pay (108) svc changed
            db.put(Integer.valueOf(102), Integer.valueOf(109)); // ! wallet_tx_charge_pay_ret (102) -> wallet_tx_charge_pay_ret (109) svc changed
            db.put(Integer.valueOf(103), Integer.valueOf(110)); // ! wallet_invoice_verify (103) -> wallet_invoice_verify (110) svc changed
            db.put(Integer.valueOf(104), Integer.valueOf(111)); // ! wallet_invoice_verify_ret (104) -> wallet_invoice_verify_ret (111) svc changed
            db.put(Integer.valueOf(105), Integer.valueOf(112)); // ! wallet_payment_verify (105) -> wallet_payment_verify (112) svc changed
            db.put(Integer.valueOf(106), Integer.valueOf(113)); // ! wallet_payment_verify_ret (106) -> wallet_payment_verify_ret (113) svc changed
            db.put(Integer.valueOf(107), Integer.valueOf(114)); // ! wallet_tx_pay (107) -> wallet_tx_pay (114) svc changed
            db.put(Integer.valueOf(108), Integer.valueOf(115)); // ! wallet_tx_pay_ret (108) -> wallet_tx_pay_ret (115) svc changed
            db.put(Integer.valueOf(109), Integer.valueOf(116)); // ! wallet_tx_new (109) -> wallet_tx_new (116) svc changed
            db.put(Integer.valueOf(110), Integer.valueOf(117)); // ! wallet_tx_new_ret (110) -> wallet_tx_new_ret (117) svc changed
            db.put(Integer.valueOf(111), Integer.valueOf(118)); // ! wallet_tx_add_section (111) -> wallet_tx_add_section (118) svc changed
            db.put(Integer.valueOf(112), Integer.valueOf(119)); // ! wallet_tx_add_section_ret (112) -> wallet_tx_add_section_ret (119) svc changed
            db.put(Integer.valueOf(113), Integer.valueOf(120)); // ! wallet_tx_add_input (113) -> wallet_tx_add_input (120) svc changed
            db.put(Integer.valueOf(114), Integer.valueOf(121)); // ! wallet_tx_add_input_ret (114) -> wallet_tx_add_input_ret (121) svc changed
            db.put(Integer.valueOf(115), Integer.valueOf(122)); // ! wallet_tx_add_output (115) -> wallet_tx_add_output (122) svc changed
            db.put(Integer.valueOf(116), Integer.valueOf(123)); // ! wallet_tx_add_output_ret (116) -> wallet_tx_add_output_ret (123) svc changed
            db.put(Integer.valueOf(117), Integer.valueOf(124)); // ! wallet_tx_sign (117) -> wallet_tx_sign (124) svc changed
            db.put(Integer.valueOf(118), Integer.valueOf(125)); // ! wallet_tx_sign_ret (118) -> wallet_tx_sign_ret (125) svc changed
            db.put(Integer.valueOf(119), Integer.valueOf(126)); // ! wallet_tx_send (119) -> wallet_tx_send (126) svc changed
            db.put(Integer.valueOf(120), Integer.valueOf(127)); // ! wallet_tx_send_ret (120) -> wallet_tx_send_ret (127) svc changed
            db.put(Integer.valueOf(121), Integer.valueOf(128)); // ! wallet_tx_decode (121) -> wallet_tx_decode (128) svc changed
            db.put(Integer.valueOf(122), Integer.valueOf(129)); // ! wallet_tx_decode_ret (122) -> wallet_tx_decode_ret (129) svc changed
            db.put(Integer.valueOf(123), Integer.valueOf(130)); // ! wallet_tx_check (123) -> wallet_tx_check (130) svc changed
            db.put(Integer.valueOf(124), Integer.valueOf(131)); // ! wallet_tx_check_ret (124) -> wallet_tx_check_ret (131) svc changed
            db.put(Integer.valueOf(125), Integer.valueOf(132)); // ! wallet_set_supply (125) -> wallet_set_supply (132) svc changed
            db.put(Integer.valueOf(126), Integer.valueOf(133)); // ! wallet_set_supply_ret (126) -> wallet_set_supply_ret (133) svc changed
            db.put(Integer.valueOf(127), Integer.valueOf(134)); // ! wallet_store_kv (127) -> wallet_store_kv (134) svc changed
            db.put(Integer.valueOf(128), Integer.valueOf(135)); // ! wallet_store_kv_ret (128) -> wallet_store_kv_ret (135) svc changed
            db.put(Integer.valueOf(129), Integer.valueOf(136)); // ! wallet_rm_kv (129) -> wallet_rm_kv (136) svc changed
            db.put(Integer.valueOf(130), Integer.valueOf(137)); // ! wallet_rm_kv_ret (130) -> wallet_rm_kv_ret (137) svc changed
            db.put(Integer.valueOf(131), Integer.valueOf(138)); // ! wallet_store_file (131) -> wallet_store_file (138) svc changed
            db.put(Integer.valueOf(132), Integer.valueOf(139)); // ! wallet_store_file_ret (132) -> wallet_store_file_ret (139) svc changed
            db.put(Integer.valueOf(133), Integer.valueOf(140)); // ! wallet_rm_file (133) -> wallet_rm_file (140) svc changed
            db.put(Integer.valueOf(134), Integer.valueOf(141)); // ! wallet_rm_file_ret (134) -> wallet_rm_file_ret (141) svc changed
            db.put(Integer.valueOf(135), Integer.valueOf(142)); // ! wallet_search (135) -> wallet_search (142) svc changed
            db.put(Integer.valueOf(136), Integer.valueOf(143)); // ! wallet_search_ret (136) -> wallet_search_ret (143) svc changed
            db.put(Integer.valueOf(137), Integer.valueOf(144)); // ! wallet_file (137) -> wallet_file (144) svc changed
            db.put(Integer.valueOf(138), Integer.valueOf(145)); // ! wallet_file_ret (138) -> wallet_file_ret (145) svc changed
            db.put(Integer.valueOf(139), Integer.valueOf(146)); // ! wallet_exec (139) -> wallet_exec (146) svc changed
            db.put(Integer.valueOf(140), Integer.valueOf(147)); // ! wallet_get_subhome (140) -> wallet_get_subhome (147) svc changed
            db.put(Integer.valueOf(141), Integer.valueOf(148)); // ! wallet_get_subhome_ret (141) -> wallet_get_subhome_ret (148) svc changed
            db.put(Integer.valueOf(142), Integer.valueOf(149)); // ! wallet_net_info (142) -> wallet_net_info (149) svc changed
            db.put(Integer.valueOf(143), Integer.valueOf(150)); // ! wallet_net_info_ret (143) -> wallet_net_info_ret (150) svc changed
            db.put(Integer.valueOf(144), Integer.valueOf(151)); // ! wallet_compilance_report (144) -> wallet_compilance_report (151) svc changed
            db.put(Integer.valueOf(145), Integer.valueOf(152)); // ! wallet_compilance_report_ret (145) -> wallet_compilance_report_ret (152) svc changed
            db.put(Integer.valueOf(146), Integer.valueOf(153)); // ! wallet_priv_key (146) -> wallet_priv_key (153) svc changed
            db.put(Integer.valueOf(147), Integer.valueOf(154)); // ! wallet_priv_key_ret (147) -> wallet_priv_key_ret (154) svc changed
            db.put(Integer.valueOf(148), Integer.valueOf(155)); // ! wallet_pub_key (148) -> wallet_pub_key (155) svc changed
            db.put(Integer.valueOf(149), Integer.valueOf(156)); // ! wallet_pub_key_ret (149) -> wallet_pub_key_ret (156) svc changed
            db.put(Integer.valueOf(150), Integer.valueOf(157)); // ! wallet_gen_keys (150) -> wallet_gen_keys (157) svc changed
            db.put(Integer.valueOf(151), Integer.valueOf(158)); // ! wallet_gen_keys_ret (151) -> wallet_gen_keys_ret (158) svc changed
            db.put(Integer.valueOf(152), Integer.valueOf(159)); // ! wallet_sign (152) -> wallet_sign (159) svc changed
            db.put(Integer.valueOf(153), Integer.valueOf(160)); // ! wallet_sign_ret (153) -> wallet_sign_ret (160) svc changed
            db.put(Integer.valueOf(154), Integer.valueOf(161)); // ! wallet_verify (154) -> wallet_verify (161) svc changed
            db.put(Integer.valueOf(155), Integer.valueOf(162)); // ! wallet_verify_ret (155) -> wallet_verify_ret (162) svc changed
            db.put(Integer.valueOf(156), Integer.valueOf(163)); // ! wallet_encrypt (156) -> wallet_encrypt (163) svc changed
            db.put(Integer.valueOf(157), Integer.valueOf(164)); // ! wallet_encrypt_ret (157) -> wallet_encrypt_ret (164) svc changed
            db.put(Integer.valueOf(158), Integer.valueOf(165)); // ! wallet_decrypt (158) -> wallet_decrypt (165) svc changed
            db.put(Integer.valueOf(159), Integer.valueOf(166)); // ! wallet_decrypt_ret (159) -> wallet_decrypt_ret (166) svc changed
            db.put(Integer.valueOf(160), Integer.valueOf(167)); // ! wallet_patch_os (160) -> wallet_patch_os (167) svc changed
            db.put(Integer.valueOf(161), Integer.valueOf(168)); // ! wallet_patch_os_ret (161) -> wallet_patch_os_ret (168) svc changed
            db.put(Integer.valueOf(162), Integer.valueOf(169)); // ! wallet_list_protocols (162) -> wallet_list_protocols (169) svc changed
            db.put(Integer.valueOf(163), Integer.valueOf(170)); // ! wallet_list_protocols_ret (163) -> wallet_list_protocols_ret (170) svc changed
            db.put(Integer.valueOf(164), Integer.valueOf(171)); // ! wallet_trade (164) -> wallet_trade (171) svc changed
            db.put(Integer.valueOf(165), Integer.valueOf(172)); // ! wallet_trade_ret (165) -> wallet_trade_ret (172) svc changed
            db.put(Integer.valueOf(166), Integer.valueOf(173)); // ! wallet_list_trades (166) -> wallet_list_trades (173) svc changed
            db.put(Integer.valueOf(167), Integer.valueOf(174)); // ! wallet_list_trades_ret (167) -> wallet_list_trades_ret (174) svc changed
            db.put(Integer.valueOf(168), Integer.valueOf(175)); // ! wallet_kill_trade (168) -> wallet_kill_trade (175) svc changed
            db.put(Integer.valueOf(169), Integer.valueOf(176)); // ! wallet_kill_trade_ret (169) -> wallet_kill_trade_ret (176) svc changed
            db.put(Integer.valueOf(170), Integer.valueOf(177)); // ! wallet_exec_trade (170) -> wallet_exec_trade (177) svc changed
            db.put(Integer.valueOf(171), Integer.valueOf(178)); // ! wallet_qr (171) -> wallet_qr (178) svc changed
            db.put(Integer.valueOf(172), Integer.valueOf(179)); // ! wallet_qr_ret (172) -> wallet_qr_ret (179) svc changed
            db.put(Integer.valueOf(173), Integer.valueOf(180)); // ! wallet_bookmark_add (173) -> wallet_bookmark_add (180) svc changed
            db.put(Integer.valueOf(174), Integer.valueOf(181)); // ! wallet_bookmark_add_ret (174) -> wallet_bookmark_add_ret (181) svc changed
            db.put(Integer.valueOf(175), Integer.valueOf(182)); // ! wallet_bookmark_delete (175) -> wallet_bookmark_delete (182) svc changed
            db.put(Integer.valueOf(176), Integer.valueOf(183)); // ! wallet_bookmark_delete_ret (176) -> wallet_bookmark_delete_ret (183) svc changed
            db.put(Integer.valueOf(177), Integer.valueOf(184)); // ! wallet_bookmark_list (177) -> wallet_bookmark_list (184) svc changed
            db.put(Integer.valueOf(178), Integer.valueOf(185)); // ! wallet_bookmark_list_ret (178) -> wallet_bookmark_list_ret (185) svc changed
            db.put(Integer.valueOf(179), Integer.valueOf(186)); // ! wallet_timeseries_list (179) -> wallet_timeseries_list (186) svc changed
            db.put(Integer.valueOf(180), Integer.valueOf(187)); // ! wallet_timeseries_list_ret (180) -> wallet_timeseries_list_ret (187) svc changed
            db.put(Integer.valueOf(181), Integer.valueOf(188)); // ! wallet_timeseries_show (181) -> wallet_timeseries_show (188) svc changed
            db.put(Integer.valueOf(182), Integer.valueOf(189)); // ! wallet_timeseries_show_ret (182) -> wallet_timeseries_show_ret (189) svc changed
            db.put(Integer.valueOf(183), Integer.valueOf(190)); // ! wallet_timeseries_new (183) -> wallet_timeseries_new (190) svc changed
            db.put(Integer.valueOf(184), Integer.valueOf(191)); // ! wallet_timeseries_new_ret (184) -> wallet_timeseries_new_ret (191) svc changed
            db.put(Integer.valueOf(185), Integer.valueOf(192)); // ! wallet_timeseries_add (185) -> wallet_timeseries_add (192) svc changed
            db.put(Integer.valueOf(186), Integer.valueOf(193)); // ! wallet_timeseries_add_ret (186) -> wallet_timeseries_add_ret (193) svc changed
            // /  (-1) -> wallet_r2r_index_hdr (194) New function
            // /  (-1) -> wallet_r2r_index_hdr_response (195) New function
            // /  (-1) -> wallet_r2r_bookmarks (196) New function
            // /  (-1) -> wallet_r2r_bookmarks_response (197) New function
            // /  (-1) -> wallet_r2r_index (198) New function
            // /  (-1) -> wallet_r2r_index_response (199) New function
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
        {
            HashMap<Integer, Integer> db = db10;
            //#include <us/api/generated/gov/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_to_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_to_prev_v>
            // / engine_print_grid (48) -> engine_print_grid (48) Same function
            // / engine_print_grid_response (49) -> engine_print_grid_response (49) Same function
            // / engine_print_socket_connections (50) -> engine_print_socket_connections (50) Same function
            // / engine_print_socket_connections_response (51) -> engine_print_socket_connections_response (51) Same function
            // / engine_allw (52) -> engine_allw (52) Same function
            // / engine_allw_response (53) -> engine_allw_response (53) Same function
            // / engine_sync (54) -> engine_sync (54) Same function
            // / engine_sync_response (55) -> engine_sync_response (55) Same function
            // / engine_reload_file (56) -> engine_reload_file (56) Same function
            // / engine_reload_file_response (57) -> engine_reload_file_response (57) Same function
            // / engine_get_component_update (58) -> engine_get_component_update (58) Same function
            // / engine_get_component_update_response (59) -> engine_get_component_update_response (59) Same function
            // / engine_get_component_hash (60) -> engine_get_component_hash (60) Same function
            // / engine_get_component_hash_response (61) -> engine_get_component_hash_response (61) Same function
            // / engine_harvest (62) -> engine_harvest (62) Same function
            // / engine_harvest_response (63) -> engine_harvest_response (63) Same function
            // / engine_world (64) -> engine_world (64) Same function
            // / engine_world_response (65) -> engine_world_response (65) Same function
            // / engine_lookup_wallet (66) -> engine_lookup_wallet (66) Same function
            // / engine_lookup_wallet_response (67) -> engine_lookup_wallet_response (67) Same function
            // / engine_random_wallet (68) -> engine_random_wallet (68) Same function
            // / engine_random_wallet_response (69) -> engine_random_wallet_response (69) Same function
            // / engine_register_w (70) -> engine_register_w (70) Same function
            // / engine_register_w_response (71) -> engine_register_w_response (71) Same function
            // / engine_conf (72) -> engine_conf (72) Same function
            // / engine_conf_response (73) -> engine_conf_response (73) Same function
            db.put(Integer.valueOf(74), Integer.valueOf(-1)); // - engine_r2r_all_index_hdr (74) ->  (-1) Removed function
            db.put(Integer.valueOf(75), Integer.valueOf(-1)); // - engine_r2r_all_index_hdr_response (75) ->  (-1) Removed function
            db.put(Integer.valueOf(76), Integer.valueOf(-1)); // - engine_r2r_all_bookmarks (76) ->  (-1) Removed function
            db.put(Integer.valueOf(77), Integer.valueOf(-1)); // - engine_r2r_all_bookmarks_response (77) ->  (-1) Removed function
            db.put(Integer.valueOf(78), Integer.valueOf(-1)); // - engine_r2r_all_index (78) ->  (-1) Removed function
            db.put(Integer.valueOf(79), Integer.valueOf(-1)); // - engine_r2r_all_index_response (79) ->  (-1) Removed function
            db.put(Integer.valueOf(80), Integer.valueOf(74)); // ! pairing_pair_device (80) -> pairing_pair_device (74) svc changed
            db.put(Integer.valueOf(81), Integer.valueOf(75)); // ! pairing_pair_device_ret (81) -> pairing_pair_device_ret (75) svc changed
            db.put(Integer.valueOf(82), Integer.valueOf(76)); // ! pairing_unpair_device (82) -> pairing_unpair_device (76) svc changed
            db.put(Integer.valueOf(83), Integer.valueOf(77)); // ! pairing_unpair_device_ret (83) -> pairing_unpair_device_ret (77) svc changed
            db.put(Integer.valueOf(84), Integer.valueOf(78)); // ! pairing_list_devices (84) -> pairing_list_devices (78) svc changed
            db.put(Integer.valueOf(85), Integer.valueOf(79)); // ! pairing_list_devices_ret (85) -> pairing_list_devices_ret (79) svc changed
            db.put(Integer.valueOf(86), Integer.valueOf(80)); // ! pairing_attempts (86) -> pairing_attempts (80) svc changed
            db.put(Integer.valueOf(87), Integer.valueOf(81)); // ! pairing_attempts_ret (87) -> pairing_attempts_ret (81) svc changed
            db.put(Integer.valueOf(88), Integer.valueOf(82)); // ! pairing_prepair_device (88) -> pairing_prepair_device (82) svc changed
            db.put(Integer.valueOf(89), Integer.valueOf(83)); // ! pairing_prepair_device_ret (89) -> pairing_prepair_device_ret (83) svc changed
            db.put(Integer.valueOf(90), Integer.valueOf(84)); // ! pairing_unprepair_device (90) -> pairing_unprepair_device (84) svc changed
            db.put(Integer.valueOf(91), Integer.valueOf(85)); // ! pairing_unprepair_device_ret (91) -> pairing_unprepair_device_ret (85) svc changed
            db.put(Integer.valueOf(92), Integer.valueOf(86)); // ! r2r_trading_msg (92) -> r2r_trading_msg (86) svc changed
            db.put(Integer.valueOf(93), Integer.valueOf(-1)); // - r2r_trading_msg2 (93) ->  (-1) Removed function
            db.put(Integer.valueOf(94), Integer.valueOf(87)); // ! wallet_balance (94) -> wallet_balance (87) svc changed
            db.put(Integer.valueOf(95), Integer.valueOf(88)); // ! wallet_balance_ret (95) -> wallet_balance_ret (88) svc changed
            db.put(Integer.valueOf(96), Integer.valueOf(89)); // ! wallet_list (96) -> wallet_list (89) svc changed
            db.put(Integer.valueOf(97), Integer.valueOf(90)); // ! wallet_list_ret (97) -> wallet_list_ret (90) svc changed
            db.put(Integer.valueOf(98), Integer.valueOf(91)); // ! wallet_recv_address (98) -> wallet_recv_address (91) svc changed
            db.put(Integer.valueOf(99), Integer.valueOf(92)); // ! wallet_recv_address_ret (99) -> wallet_recv_address_ret (92) svc changed
            db.put(Integer.valueOf(100), Integer.valueOf(93)); // ! wallet_new_address (100) -> wallet_new_address (93) svc changed
            db.put(Integer.valueOf(101), Integer.valueOf(94)); // ! wallet_new_address_ret (101) -> wallet_new_address_ret (94) svc changed
            db.put(Integer.valueOf(102), Integer.valueOf(95)); // ! wallet_add_address (102) -> wallet_add_address (95) svc changed
            db.put(Integer.valueOf(103), Integer.valueOf(96)); // ! wallet_add_address_ret (103) -> wallet_add_address_ret (96) svc changed
            db.put(Integer.valueOf(104), Integer.valueOf(97)); // ! wallet_transfer (104) -> wallet_transfer (97) svc changed
            db.put(Integer.valueOf(105), Integer.valueOf(98)); // ! wallet_transfer_ret (105) -> wallet_transfer_ret (98) svc changed
            db.put(Integer.valueOf(106), Integer.valueOf(99)); // ! wallet_transfer_from (106) -> wallet_transfer_from (99) svc changed
            db.put(Integer.valueOf(107), Integer.valueOf(100)); // ! wallet_transfer_from_ret (107) -> wallet_transfer_from_ret (100) svc changed
            db.put(Integer.valueOf(108), Integer.valueOf(101)); // ! wallet_tx_charge_pay (108) -> wallet_tx_charge_pay (101) svc changed
            db.put(Integer.valueOf(109), Integer.valueOf(102)); // ! wallet_tx_charge_pay_ret (109) -> wallet_tx_charge_pay_ret (102) svc changed
            db.put(Integer.valueOf(110), Integer.valueOf(103)); // ! wallet_invoice_verify (110) -> wallet_invoice_verify (103) svc changed
            db.put(Integer.valueOf(111), Integer.valueOf(104)); // ! wallet_invoice_verify_ret (111) -> wallet_invoice_verify_ret (104) svc changed
            db.put(Integer.valueOf(112), Integer.valueOf(105)); // ! wallet_payment_verify (112) -> wallet_payment_verify (105) svc changed
            db.put(Integer.valueOf(113), Integer.valueOf(106)); // ! wallet_payment_verify_ret (113) -> wallet_payment_verify_ret (106) svc changed
            db.put(Integer.valueOf(114), Integer.valueOf(107)); // ! wallet_tx_pay (114) -> wallet_tx_pay (107) svc changed
            db.put(Integer.valueOf(115), Integer.valueOf(108)); // ! wallet_tx_pay_ret (115) -> wallet_tx_pay_ret (108) svc changed
            db.put(Integer.valueOf(116), Integer.valueOf(109)); // ! wallet_tx_new (116) -> wallet_tx_new (109) svc changed
            db.put(Integer.valueOf(117), Integer.valueOf(110)); // ! wallet_tx_new_ret (117) -> wallet_tx_new_ret (110) svc changed
            db.put(Integer.valueOf(118), Integer.valueOf(111)); // ! wallet_tx_add_section (118) -> wallet_tx_add_section (111) svc changed
            db.put(Integer.valueOf(119), Integer.valueOf(112)); // ! wallet_tx_add_section_ret (119) -> wallet_tx_add_section_ret (112) svc changed
            db.put(Integer.valueOf(120), Integer.valueOf(113)); // ! wallet_tx_add_input (120) -> wallet_tx_add_input (113) svc changed
            db.put(Integer.valueOf(121), Integer.valueOf(114)); // ! wallet_tx_add_input_ret (121) -> wallet_tx_add_input_ret (114) svc changed
            db.put(Integer.valueOf(122), Integer.valueOf(115)); // ! wallet_tx_add_output (122) -> wallet_tx_add_output (115) svc changed
            db.put(Integer.valueOf(123), Integer.valueOf(116)); // ! wallet_tx_add_output_ret (123) -> wallet_tx_add_output_ret (116) svc changed
            db.put(Integer.valueOf(124), Integer.valueOf(117)); // ! wallet_tx_sign (124) -> wallet_tx_sign (117) svc changed
            db.put(Integer.valueOf(125), Integer.valueOf(118)); // ! wallet_tx_sign_ret (125) -> wallet_tx_sign_ret (118) svc changed
            db.put(Integer.valueOf(126), Integer.valueOf(119)); // ! wallet_tx_send (126) -> wallet_tx_send (119) svc changed
            db.put(Integer.valueOf(127), Integer.valueOf(120)); // ! wallet_tx_send_ret (127) -> wallet_tx_send_ret (120) svc changed
            db.put(Integer.valueOf(128), Integer.valueOf(121)); // ! wallet_tx_decode (128) -> wallet_tx_decode (121) svc changed
            db.put(Integer.valueOf(129), Integer.valueOf(122)); // ! wallet_tx_decode_ret (129) -> wallet_tx_decode_ret (122) svc changed
            db.put(Integer.valueOf(130), Integer.valueOf(123)); // ! wallet_tx_check (130) -> wallet_tx_check (123) svc changed
            db.put(Integer.valueOf(131), Integer.valueOf(124)); // ! wallet_tx_check_ret (131) -> wallet_tx_check_ret (124) svc changed
            db.put(Integer.valueOf(132), Integer.valueOf(125)); // ! wallet_set_supply (132) -> wallet_set_supply (125) svc changed
            db.put(Integer.valueOf(133), Integer.valueOf(126)); // ! wallet_set_supply_ret (133) -> wallet_set_supply_ret (126) svc changed
            db.put(Integer.valueOf(134), Integer.valueOf(127)); // ! wallet_store_kv (134) -> wallet_store_kv (127) svc changed
            db.put(Integer.valueOf(135), Integer.valueOf(128)); // ! wallet_store_kv_ret (135) -> wallet_store_kv_ret (128) svc changed
            db.put(Integer.valueOf(136), Integer.valueOf(129)); // ! wallet_rm_kv (136) -> wallet_rm_kv (129) svc changed
            db.put(Integer.valueOf(137), Integer.valueOf(130)); // ! wallet_rm_kv_ret (137) -> wallet_rm_kv_ret (130) svc changed
            db.put(Integer.valueOf(138), Integer.valueOf(131)); // ! wallet_store_file (138) -> wallet_store_file (131) svc changed
            db.put(Integer.valueOf(139), Integer.valueOf(132)); // ! wallet_store_file_ret (139) -> wallet_store_file_ret (132) svc changed
            db.put(Integer.valueOf(140), Integer.valueOf(133)); // ! wallet_rm_file (140) -> wallet_rm_file (133) svc changed
            db.put(Integer.valueOf(141), Integer.valueOf(134)); // ! wallet_rm_file_ret (141) -> wallet_rm_file_ret (134) svc changed
            db.put(Integer.valueOf(142), Integer.valueOf(135)); // ! wallet_search (142) -> wallet_search (135) svc changed
            db.put(Integer.valueOf(143), Integer.valueOf(136)); // ! wallet_search_ret (143) -> wallet_search_ret (136) svc changed
            db.put(Integer.valueOf(144), Integer.valueOf(137)); // ! wallet_file (144) -> wallet_file (137) svc changed
            db.put(Integer.valueOf(145), Integer.valueOf(138)); // ! wallet_file_ret (145) -> wallet_file_ret (138) svc changed
            db.put(Integer.valueOf(146), Integer.valueOf(139)); // ! wallet_exec (146) -> wallet_exec (139) svc changed
            db.put(Integer.valueOf(147), Integer.valueOf(140)); // ! wallet_get_subhome (147) -> wallet_get_subhome (140) svc changed
            db.put(Integer.valueOf(148), Integer.valueOf(141)); // ! wallet_get_subhome_ret (148) -> wallet_get_subhome_ret (141) svc changed
            db.put(Integer.valueOf(149), Integer.valueOf(142)); // ! wallet_net_info (149) -> wallet_net_info (142) svc changed
            db.put(Integer.valueOf(150), Integer.valueOf(143)); // ! wallet_net_info_ret (150) -> wallet_net_info_ret (143) svc changed
            db.put(Integer.valueOf(151), Integer.valueOf(144)); // ! wallet_compilance_report (151) -> wallet_compilance_report (144) svc changed
            db.put(Integer.valueOf(152), Integer.valueOf(145)); // ! wallet_compilance_report_ret (152) -> wallet_compilance_report_ret (145) svc changed
            db.put(Integer.valueOf(153), Integer.valueOf(146)); // ! wallet_priv_key (153) -> wallet_priv_key (146) svc changed
            db.put(Integer.valueOf(154), Integer.valueOf(147)); // ! wallet_priv_key_ret (154) -> wallet_priv_key_ret (147) svc changed
            db.put(Integer.valueOf(155), Integer.valueOf(148)); // ! wallet_pub_key (155) -> wallet_pub_key (148) svc changed
            db.put(Integer.valueOf(156), Integer.valueOf(149)); // ! wallet_pub_key_ret (156) -> wallet_pub_key_ret (149) svc changed
            db.put(Integer.valueOf(157), Integer.valueOf(150)); // ! wallet_gen_keys (157) -> wallet_gen_keys (150) svc changed
            db.put(Integer.valueOf(158), Integer.valueOf(151)); // ! wallet_gen_keys_ret (158) -> wallet_gen_keys_ret (151) svc changed
            db.put(Integer.valueOf(159), Integer.valueOf(152)); // ! wallet_sign (159) -> wallet_sign (152) svc changed
            db.put(Integer.valueOf(160), Integer.valueOf(153)); // ! wallet_sign_ret (160) -> wallet_sign_ret (153) svc changed
            db.put(Integer.valueOf(161), Integer.valueOf(154)); // ! wallet_verify (161) -> wallet_verify (154) svc changed
            db.put(Integer.valueOf(162), Integer.valueOf(155)); // ! wallet_verify_ret (162) -> wallet_verify_ret (155) svc changed
            db.put(Integer.valueOf(163), Integer.valueOf(156)); // ! wallet_encrypt (163) -> wallet_encrypt (156) svc changed
            db.put(Integer.valueOf(164), Integer.valueOf(157)); // ! wallet_encrypt_ret (164) -> wallet_encrypt_ret (157) svc changed
            db.put(Integer.valueOf(165), Integer.valueOf(158)); // ! wallet_decrypt (165) -> wallet_decrypt (158) svc changed
            db.put(Integer.valueOf(166), Integer.valueOf(159)); // ! wallet_decrypt_ret (166) -> wallet_decrypt_ret (159) svc changed
            db.put(Integer.valueOf(167), Integer.valueOf(160)); // ! wallet_patch_os (167) -> wallet_patch_os (160) svc changed
            db.put(Integer.valueOf(168), Integer.valueOf(161)); // ! wallet_patch_os_ret (168) -> wallet_patch_os_ret (161) svc changed
            db.put(Integer.valueOf(169), Integer.valueOf(162)); // ! wallet_list_protocols (169) -> wallet_list_protocols (162) svc changed
            db.put(Integer.valueOf(170), Integer.valueOf(163)); // ! wallet_list_protocols_ret (170) -> wallet_list_protocols_ret (163) svc changed
            db.put(Integer.valueOf(171), Integer.valueOf(164)); // ! wallet_trade (171) -> wallet_trade (164) svc changed
            db.put(Integer.valueOf(172), Integer.valueOf(165)); // ! wallet_trade_ret (172) -> wallet_trade_ret (165) svc changed
            db.put(Integer.valueOf(173), Integer.valueOf(166)); // ! wallet_list_trades (173) -> wallet_list_trades (166) svc changed
            db.put(Integer.valueOf(174), Integer.valueOf(167)); // ! wallet_list_trades_ret (174) -> wallet_list_trades_ret (167) svc changed
            db.put(Integer.valueOf(175), Integer.valueOf(168)); // ! wallet_kill_trade (175) -> wallet_kill_trade (168) svc changed
            db.put(Integer.valueOf(176), Integer.valueOf(169)); // ! wallet_kill_trade_ret (176) -> wallet_kill_trade_ret (169) svc changed
            db.put(Integer.valueOf(177), Integer.valueOf(170)); // ! wallet_exec_trade (177) -> wallet_exec_trade (170) svc changed
            db.put(Integer.valueOf(178), Integer.valueOf(171)); // ! wallet_qr (178) -> wallet_qr (171) svc changed
            db.put(Integer.valueOf(179), Integer.valueOf(172)); // ! wallet_qr_ret (179) -> wallet_qr_ret (172) svc changed
            db.put(Integer.valueOf(180), Integer.valueOf(173)); // ! wallet_bookmark_add (180) -> wallet_bookmark_add (173) svc changed
            db.put(Integer.valueOf(181), Integer.valueOf(174)); // ! wallet_bookmark_add_ret (181) -> wallet_bookmark_add_ret (174) svc changed
            db.put(Integer.valueOf(182), Integer.valueOf(175)); // ! wallet_bookmark_delete (182) -> wallet_bookmark_delete (175) svc changed
            db.put(Integer.valueOf(183), Integer.valueOf(176)); // ! wallet_bookmark_delete_ret (183) -> wallet_bookmark_delete_ret (176) svc changed
            db.put(Integer.valueOf(184), Integer.valueOf(177)); // ! wallet_bookmark_list (184) -> wallet_bookmark_list (177) svc changed
            db.put(Integer.valueOf(185), Integer.valueOf(178)); // ! wallet_bookmark_list_ret (185) -> wallet_bookmark_list_ret (178) svc changed
            db.put(Integer.valueOf(186), Integer.valueOf(179)); // ! wallet_timeseries_list (186) -> wallet_timeseries_list (179) svc changed
            db.put(Integer.valueOf(187), Integer.valueOf(180)); // ! wallet_timeseries_list_ret (187) -> wallet_timeseries_list_ret (180) svc changed
            db.put(Integer.valueOf(188), Integer.valueOf(181)); // ! wallet_timeseries_show (188) -> wallet_timeseries_show (181) svc changed
            db.put(Integer.valueOf(189), Integer.valueOf(182)); // ! wallet_timeseries_show_ret (189) -> wallet_timeseries_show_ret (182) svc changed
            db.put(Integer.valueOf(190), Integer.valueOf(183)); // ! wallet_timeseries_new (190) -> wallet_timeseries_new (183) svc changed
            db.put(Integer.valueOf(191), Integer.valueOf(184)); // ! wallet_timeseries_new_ret (191) -> wallet_timeseries_new_ret (184) svc changed
            db.put(Integer.valueOf(192), Integer.valueOf(185)); // ! wallet_timeseries_add (192) -> wallet_timeseries_add (185) svc changed
            db.put(Integer.valueOf(193), Integer.valueOf(186)); // ! wallet_timeseries_add_ret (193) -> wallet_timeseries_add_ret (186) svc changed
            db.put(Integer.valueOf(194), Integer.valueOf(-1)); // - wallet_r2r_index_hdr (194) ->  (-1) Removed function
            db.put(Integer.valueOf(195), Integer.valueOf(-1)); // - wallet_r2r_index_hdr_response (195) ->  (-1) Removed function
            db.put(Integer.valueOf(196), Integer.valueOf(-1)); // - wallet_r2r_bookmarks (196) ->  (-1) Removed function
            db.put(Integer.valueOf(197), Integer.valueOf(-1)); // - wallet_r2r_bookmarks_response (197) ->  (-1) Removed function
            db.put(Integer.valueOf(198), Integer.valueOf(-1)); // - wallet_r2r_index (198) ->  (-1) Removed function
            db.put(Integer.valueOf(199), Integer.valueOf(-1)); // - wallet_r2r_index_response (199) ->  (-1) Removed function
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
   }

    public void from_prev(svc_t svc) {
        Integer i = db01.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    public void to_prev(svc_t svc) {
        Integer i = db10.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    HashMap<Integer, Integer> db01 = new HashMap<Integer, Integer>();
    HashMap<Integer, Integer> db10 = new HashMap<Integer, Integer>();

}

