//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.wallet.engine;
import us.CFG;                                                                                 // CFG
import static java.util.Map.entry;                                                             // entry
import java.util.HashMap;                                                                      // HashMap
import static us.gov.socket.types.*;                                                           // *
import java.util.Map;                                                                          // Map

public class svcfish_t {

    static void log(final String line) {                        //--strip
        CFG.log_gov("svcfish_t: " + line);                      //--strip
    }                                                           //--strip

    public svcfish_t() {
        {
            HashMap<Integer, Integer> db = db01;
            //#include <us/api/generated/gov/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_from_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_from_prev_v>
            // / engine_print_grid (48) -> engine_print_grid (48) Same function
            // / engine_print_grid_response (49) -> engine_print_grid_response (49) Same function
            // / engine_print_socket_connections (50) -> engine_print_socket_connections (50) Same function
            // / engine_print_socket_connections_response (51) -> engine_print_socket_connections_response (51) Same function
            // / engine_allw (52) -> engine_allw (52) Same function
            // / engine_allw_response (53) -> engine_allw_response (53) Same function
            // / engine_sync (54) -> engine_sync (54) Same function
            // / engine_sync_response (55) -> engine_sync_response (55) Same function
            // / engine_reload_file (56) -> engine_reload_file (56) Same function
            // / engine_reload_file_response (57) -> engine_reload_file_response (57) Same function
            // / engine_get_component_update (58) -> engine_get_component_update (58) Same function
            // / engine_get_component_update_response (59) -> engine_get_component_update_response (59) Same function
            // / engine_get_component_hash (60) -> engine_get_component_hash (60) Same function
            // / engine_get_component_hash_response (61) -> engine_get_component_hash_response (61) Same function
            // / engine_harvest (62) -> engine_harvest (62) Same function
            // / engine_harvest_response (63) -> engine_harvest_response (63) Same function
            // / engine_world (64) -> engine_world (64) Same function
            // / engine_world_response (65) -> engine_world_response (65) Same function
            // / engine_lookup_wallet (66) -> engine_lookup_wallet (66) Same function
            // / engine_lookup_wallet_response (67) -> engine_lookup_wallet_response (67) Same function
            // / engine_random_wallet (68) -> engine_random_wallet (68) Same function
            // / engine_random_wallet_response (69) -> engine_random_wallet_response (69) Same function
            // / engine_register_w (70) -> engine_register_w (70) Same function
            // / engine_register_w_response (71) -> engine_register_w_response (71) Same function
            // / engine_conf (72) -> engine_conf (72) Same function
            // / engine_conf_response (73) -> engine_conf_response (73) Same function
            // / engine_r2r_all_index_hdr (74) -> engine_r2r_all_index_hdr (74) Same function
            // / engine_r2r_all_index_hdr_response (75) -> engine_r2r_all_index_hdr_response (75) Same function
            // / engine_r2r_all_bookmarks (76) -> engine_r2r_all_bookmarks (76) Same function
            // / engine_r2r_all_bookmarks_response (77) -> engine_r2r_all_bookmarks_response (77) Same function
            // / engine_r2r_all_index (78) -> engine_r2r_all_index (78) Same function
            // / engine_r2r_all_index_response (79) -> engine_r2r_all_index_response (79) Same function
            // / pairing_pair_device (80) -> pairing_pair_device (80) Same function
            // / pairing_pair_device_response (81) -> pairing_pair_device_response (81) Same function
            // / pairing_unpair_device (82) -> pairing_unpair_device (82) Same function
            // / pairing_unpair_device_response (83) -> pairing_unpair_device_response (83) Same function
            // / pairing_list_devices (84) -> pairing_list_devices (84) Same function
            // / pairing_list_devices_response (85) -> pairing_list_devices_response (85) Same function
            // / pairing_attempts (86) -> pairing_attempts (86) Same function
            // / pairing_attempts_response (87) -> pairing_attempts_response (87) Same function
            // / pairing_prepair_device (88) -> pairing_prepair_device (88) Same function
            // / pairing_prepair_device_response (89) -> pairing_prepair_device_response (89) Same function
            // / pairing_unprepair_device (90) -> pairing_unprepair_device (90) Same function
            // / pairing_unprepair_device_response (91) -> pairing_unprepair_device_response (91) Same function
            // / r2r_trading_msg (92) -> r2r_trading_msg (92) Same function
            // / r2r_trading_msg2 (93) -> r2r_trading_msg2 (93) Same function
            // / wallet_balance (94) -> wallet_balance (94) Same function
            // / wallet_balance_response (95) -> wallet_balance_response (95) Same function
            // / wallet_list (96) -> wallet_list (96) Same function
            // / wallet_list_response (97) -> wallet_list_response (97) Same function
            // / wallet_recv_address (98) -> wallet_recv_address (98) Same function
            // / wallet_recv_address_response (99) -> wallet_recv_address_response (99) Same function
            // / wallet_new_address (100) -> wallet_new_address (100) Same function
            // / wallet_new_address_response (101) -> wallet_new_address_response (101) Same function
            // / wallet_add_address (102) -> wallet_add_address (102) Same function
            // / wallet_add_address_response (103) -> wallet_add_address_response (103) Same function
            // / wallet_transfer (104) -> wallet_transfer (104) Same function
            // / wallet_transfer_response (105) -> wallet_transfer_response (105) Same function
            // / wallet_transfer_from (106) -> wallet_transfer_from (106) Same function
            // / wallet_transfer_from_response (107) -> wallet_transfer_from_response (107) Same function
            // / wallet_tx_charge_pay (108) -> wallet_tx_charge_pay (108) Same function
            // / wallet_tx_charge_pay_response (109) -> wallet_tx_charge_pay_response (109) Same function
            // / wallet_invoice_verify (110) -> wallet_invoice_verify (110) Same function
            // / wallet_invoice_verify_response (111) -> wallet_invoice_verify_response (111) Same function
            // / wallet_payment_verify (112) -> wallet_payment_verify (112) Same function
            // / wallet_payment_verify_response (113) -> wallet_payment_verify_response (113) Same function
            // / wallet_tx_pay (114) -> wallet_tx_pay (114) Same function
            // / wallet_tx_pay_response (115) -> wallet_tx_pay_response (115) Same function
            // / wallet_tx_new (116) -> wallet_tx_new (116) Same function
            // / wallet_tx_new_response (117) -> wallet_tx_new_response (117) Same function
            // / wallet_tx_add_section (118) -> wallet_tx_add_section (118) Same function
            // / wallet_tx_add_section_response (119) -> wallet_tx_add_section_response (119) Same function
            // / wallet_tx_add_input (120) -> wallet_tx_add_input (120) Same function
            // / wallet_tx_add_input_response (121) -> wallet_tx_add_input_response (121) Same function
            // / wallet_tx_add_output (122) -> wallet_tx_add_output (122) Same function
            // / wallet_tx_add_output_response (123) -> wallet_tx_add_output_response (123) Same function
            // / wallet_tx_sign (124) -> wallet_tx_sign (124) Same function
            // / wallet_tx_sign_response (125) -> wallet_tx_sign_response (125) Same function
            // / wallet_tx_send (126) -> wallet_tx_send (126) Same function
            // / wallet_tx_send_response (127) -> wallet_tx_send_response (127) Same function
            // / wallet_tx_decode (128) -> wallet_tx_decode (128) Same function
            // / wallet_tx_decode_response (129) -> wallet_tx_decode_response (129) Same function
            // / wallet_tx_check (130) -> wallet_tx_check (130) Same function
            // / wallet_tx_check_response (131) -> wallet_tx_check_response (131) Same function
            // / wallet_set_supply (132) -> wallet_set_supply (132) Same function
            // / wallet_set_supply_response (133) -> wallet_set_supply_response (133) Same function
            // / wallet_store_kv (134) -> wallet_store_kv (134) Same function
            // / wallet_store_kv_response (135) -> wallet_store_kv_response (135) Same function
            // / wallet_rm_kv (136) -> wallet_rm_kv (136) Same function
            // / wallet_rm_kv_response (137) -> wallet_rm_kv_response (137) Same function
            // / wallet_store_file (138) -> wallet_store_file (138) Same function
            // / wallet_store_file_response (139) -> wallet_store_file_response (139) Same function
            // / wallet_rm_file (140) -> wallet_rm_file (140) Same function
            // / wallet_rm_file_response (141) -> wallet_rm_file_response (141) Same function
            // / wallet_search (142) -> wallet_search (142) Same function
            // / wallet_search_response (143) -> wallet_search_response (143) Same function
            // / wallet_file (144) -> wallet_file (144) Same function
            // / wallet_file_response (145) -> wallet_file_response (145) Same function
            // / wallet_exec (146) -> wallet_exec (146) Same function
            // / wallet_get_subhome (147) -> wallet_get_subhome (147) Same function
            // / wallet_get_subhome_response (148) -> wallet_get_subhome_response (148) Same function
            // / wallet_net_info (149) -> wallet_net_info (149) Same function
            // / wallet_net_info_response (150) -> wallet_net_info_response (150) Same function
            // / wallet_compilance_report (151) -> wallet_compilance_report (151) Same function
            // / wallet_compilance_report_response (152) -> wallet_compilance_report_response (152) Same function
            // / wallet_priv_key (153) -> wallet_priv_key (153) Same function
            // / wallet_priv_key_response (154) -> wallet_priv_key_response (154) Same function
            // / wallet_pub_key (155) -> wallet_pub_key (155) Same function
            // / wallet_pub_key_response (156) -> wallet_pub_key_response (156) Same function
            // / wallet_gen_keys (157) -> wallet_gen_keys (157) Same function
            // / wallet_gen_keys_response (158) -> wallet_gen_keys_response (158) Same function
            // / wallet_sign (159) -> wallet_sign (159) Same function
            // / wallet_sign_response (160) -> wallet_sign_response (160) Same function
            // / wallet_verify (161) -> wallet_verify (161) Same function
            // / wallet_verify_response (162) -> wallet_verify_response (162) Same function
            // / wallet_encrypt (163) -> wallet_encrypt (163) Same function
            // / wallet_encrypt_response (164) -> wallet_encrypt_response (164) Same function
            // / wallet_decrypt (165) -> wallet_decrypt (165) Same function
            // / wallet_decrypt_response (166) -> wallet_decrypt_response (166) Same function
            // / wallet_patch_os (167) -> wallet_patch_os (167) Same function
            // / wallet_patch_os_response (168) -> wallet_patch_os_response (168) Same function
            // / wallet_list_protocols (169) -> wallet_list_protocols (169) Same function
            // / wallet_list_protocols_response (170) -> wallet_list_protocols_response (170) Same function
            // / wallet_trade (171) -> wallet_trade (171) Same function
            // / wallet_trade_response (172) -> wallet_trade_response (172) Same function
            // / wallet_list_trades (173) -> wallet_list_trades (173) Same function
            // / wallet_list_trades_response (174) -> wallet_list_trades_response (174) Same function
            // / wallet_kill_trade (175) -> wallet_kill_trade (175) Same function
            // / wallet_kill_trade_response (176) -> wallet_kill_trade_response (176) Same function
            // / wallet_exec_trade (177) -> wallet_exec_trade (177) Same function
            // / wallet_qr (178) -> wallet_qr (178) Same function
            // / wallet_qr_response (179) -> wallet_qr_response (179) Same function
            // / wallet_bookmark_add (180) -> wallet_bookmark_add (180) Same function
            // / wallet_bookmark_add_response (181) -> wallet_bookmark_add_response (181) Same function
            // / wallet_bookmark_delete (182) -> wallet_bookmark_delete (182) Same function
            // / wallet_bookmark_delete_response (183) -> wallet_bookmark_delete_response (183) Same function
            // / wallet_bookmark_list (184) -> wallet_bookmark_list (184) Same function
            // / wallet_bookmark_list_response (185) -> wallet_bookmark_list_response (185) Same function
            // / wallet_timeseries_list (186) -> wallet_timeseries_list (186) Same function
            // / wallet_timeseries_list_response (187) -> wallet_timeseries_list_response (187) Same function
            // / wallet_timeseries_show (188) -> wallet_timeseries_show (188) Same function
            // / wallet_timeseries_show_response (189) -> wallet_timeseries_show_response (189) Same function
            // / wallet_timeseries_new (190) -> wallet_timeseries_new (190) Same function
            // / wallet_timeseries_new_response (191) -> wallet_timeseries_new_response (191) Same function
            // / wallet_timeseries_add (192) -> wallet_timeseries_add (192) Same function
            // / wallet_timeseries_add_response (193) -> wallet_timeseries_add_response (193) Same function
            // / wallet_r2r_index_hdr (194) -> wallet_r2r_index_hdr (194) Same function
            // / wallet_r2r_index_hdr_response (195) -> wallet_r2r_index_hdr_response (195) Same function
            // / wallet_r2r_bookmarks (196) -> wallet_r2r_bookmarks (196) Same function
            // / wallet_r2r_bookmarks_response (197) -> wallet_r2r_bookmarks_response (197) Same function
            // / wallet_r2r_index (198) -> wallet_r2r_index (198) Same function
            // / wallet_r2r_index_response (199) -> wallet_r2r_index_response (199) Same function
            // /  (-1) -> wallet_cert_create (200) New function
            // /  (-1) -> wallet_cert_create_response (201) New function
            // /  (-1) -> wallet_cert_import (202) New function
            // /  (-1) -> wallet_cert_import_response (203) New function
            // /  (-1) -> wallet_cert_list (204) New function
            // /  (-1) -> wallet_cert_list_response (205) New function
            // /  (-1) -> wallet_cert_get (206) New function
            // /  (-1) -> wallet_cert_get_response (207) New function
            // /  (-1) -> wallet_cert_show (208) New function
            // /  (-1) -> wallet_cert_show_response (209) New function
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
        {
            HashMap<Integer, Integer> db = db10;
            //#include <us/api/generated/gov/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_to_prev_v>
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_to_prev_v>
            // / engine_print_grid (48) -> engine_print_grid (48) Same function
            // / engine_print_grid_response (49) -> engine_print_grid_response (49) Same function
            // / engine_print_socket_connections (50) -> engine_print_socket_connections (50) Same function
            // / engine_print_socket_connections_response (51) -> engine_print_socket_connections_response (51) Same function
            // / engine_allw (52) -> engine_allw (52) Same function
            // / engine_allw_response (53) -> engine_allw_response (53) Same function
            // / engine_sync (54) -> engine_sync (54) Same function
            // / engine_sync_response (55) -> engine_sync_response (55) Same function
            // / engine_reload_file (56) -> engine_reload_file (56) Same function
            // / engine_reload_file_response (57) -> engine_reload_file_response (57) Same function
            // / engine_get_component_update (58) -> engine_get_component_update (58) Same function
            // / engine_get_component_update_response (59) -> engine_get_component_update_response (59) Same function
            // / engine_get_component_hash (60) -> engine_get_component_hash (60) Same function
            // / engine_get_component_hash_response (61) -> engine_get_component_hash_response (61) Same function
            // / engine_harvest (62) -> engine_harvest (62) Same function
            // / engine_harvest_response (63) -> engine_harvest_response (63) Same function
            // / engine_world (64) -> engine_world (64) Same function
            // / engine_world_response (65) -> engine_world_response (65) Same function
            // / engine_lookup_wallet (66) -> engine_lookup_wallet (66) Same function
            // / engine_lookup_wallet_response (67) -> engine_lookup_wallet_response (67) Same function
            // / engine_random_wallet (68) -> engine_random_wallet (68) Same function
            // / engine_random_wallet_response (69) -> engine_random_wallet_response (69) Same function
            // / engine_register_w (70) -> engine_register_w (70) Same function
            // / engine_register_w_response (71) -> engine_register_w_response (71) Same function
            // / engine_conf (72) -> engine_conf (72) Same function
            // / engine_conf_response (73) -> engine_conf_response (73) Same function
            // / engine_r2r_all_index_hdr (74) -> engine_r2r_all_index_hdr (74) Same function
            // / engine_r2r_all_index_hdr_response (75) -> engine_r2r_all_index_hdr_response (75) Same function
            // / engine_r2r_all_bookmarks (76) -> engine_r2r_all_bookmarks (76) Same function
            // / engine_r2r_all_bookmarks_response (77) -> engine_r2r_all_bookmarks_response (77) Same function
            // / engine_r2r_all_index (78) -> engine_r2r_all_index (78) Same function
            // / engine_r2r_all_index_response (79) -> engine_r2r_all_index_response (79) Same function
            // / pairing_pair_device (80) -> pairing_pair_device (80) Same function
            // / pairing_pair_device_response (81) -> pairing_pair_device_response (81) Same function
            // / pairing_unpair_device (82) -> pairing_unpair_device (82) Same function
            // / pairing_unpair_device_response (83) -> pairing_unpair_device_response (83) Same function
            // / pairing_list_devices (84) -> pairing_list_devices (84) Same function
            // / pairing_list_devices_response (85) -> pairing_list_devices_response (85) Same function
            // / pairing_attempts (86) -> pairing_attempts (86) Same function
            // / pairing_attempts_response (87) -> pairing_attempts_response (87) Same function
            // / pairing_prepair_device (88) -> pairing_prepair_device (88) Same function
            // / pairing_prepair_device_response (89) -> pairing_prepair_device_response (89) Same function
            // / pairing_unprepair_device (90) -> pairing_unprepair_device (90) Same function
            // / pairing_unprepair_device_response (91) -> pairing_unprepair_device_response (91) Same function
            // / r2r_trading_msg (92) -> r2r_trading_msg (92) Same function
            // / r2r_trading_msg2 (93) -> r2r_trading_msg2 (93) Same function
            // / wallet_balance (94) -> wallet_balance (94) Same function
            // / wallet_balance_response (95) -> wallet_balance_response (95) Same function
            // / wallet_list (96) -> wallet_list (96) Same function
            // / wallet_list_response (97) -> wallet_list_response (97) Same function
            // / wallet_recv_address (98) -> wallet_recv_address (98) Same function
            // / wallet_recv_address_response (99) -> wallet_recv_address_response (99) Same function
            // / wallet_new_address (100) -> wallet_new_address (100) Same function
            // / wallet_new_address_response (101) -> wallet_new_address_response (101) Same function
            // / wallet_add_address (102) -> wallet_add_address (102) Same function
            // / wallet_add_address_response (103) -> wallet_add_address_response (103) Same function
            // / wallet_transfer (104) -> wallet_transfer (104) Same function
            // / wallet_transfer_response (105) -> wallet_transfer_response (105) Same function
            // / wallet_transfer_from (106) -> wallet_transfer_from (106) Same function
            // / wallet_transfer_from_response (107) -> wallet_transfer_from_response (107) Same function
            // / wallet_tx_charge_pay (108) -> wallet_tx_charge_pay (108) Same function
            // / wallet_tx_charge_pay_response (109) -> wallet_tx_charge_pay_response (109) Same function
            // / wallet_invoice_verify (110) -> wallet_invoice_verify (110) Same function
            // / wallet_invoice_verify_response (111) -> wallet_invoice_verify_response (111) Same function
            // / wallet_payment_verify (112) -> wallet_payment_verify (112) Same function
            // / wallet_payment_verify_response (113) -> wallet_payment_verify_response (113) Same function
            // / wallet_tx_pay (114) -> wallet_tx_pay (114) Same function
            // / wallet_tx_pay_response (115) -> wallet_tx_pay_response (115) Same function
            // / wallet_tx_new (116) -> wallet_tx_new (116) Same function
            // / wallet_tx_new_response (117) -> wallet_tx_new_response (117) Same function
            // / wallet_tx_add_section (118) -> wallet_tx_add_section (118) Same function
            // / wallet_tx_add_section_response (119) -> wallet_tx_add_section_response (119) Same function
            // / wallet_tx_add_input (120) -> wallet_tx_add_input (120) Same function
            // / wallet_tx_add_input_response (121) -> wallet_tx_add_input_response (121) Same function
            // / wallet_tx_add_output (122) -> wallet_tx_add_output (122) Same function
            // / wallet_tx_add_output_response (123) -> wallet_tx_add_output_response (123) Same function
            // / wallet_tx_sign (124) -> wallet_tx_sign (124) Same function
            // / wallet_tx_sign_response (125) -> wallet_tx_sign_response (125) Same function
            // / wallet_tx_send (126) -> wallet_tx_send (126) Same function
            // / wallet_tx_send_response (127) -> wallet_tx_send_response (127) Same function
            // / wallet_tx_decode (128) -> wallet_tx_decode (128) Same function
            // / wallet_tx_decode_response (129) -> wallet_tx_decode_response (129) Same function
            // / wallet_tx_check (130) -> wallet_tx_check (130) Same function
            // / wallet_tx_check_response (131) -> wallet_tx_check_response (131) Same function
            // / wallet_set_supply (132) -> wallet_set_supply (132) Same function
            // / wallet_set_supply_response (133) -> wallet_set_supply_response (133) Same function
            // / wallet_store_kv (134) -> wallet_store_kv (134) Same function
            // / wallet_store_kv_response (135) -> wallet_store_kv_response (135) Same function
            // / wallet_rm_kv (136) -> wallet_rm_kv (136) Same function
            // / wallet_rm_kv_response (137) -> wallet_rm_kv_response (137) Same function
            // / wallet_store_file (138) -> wallet_store_file (138) Same function
            // / wallet_store_file_response (139) -> wallet_store_file_response (139) Same function
            // / wallet_rm_file (140) -> wallet_rm_file (140) Same function
            // / wallet_rm_file_response (141) -> wallet_rm_file_response (141) Same function
            // / wallet_search (142) -> wallet_search (142) Same function
            // / wallet_search_response (143) -> wallet_search_response (143) Same function
            // / wallet_file (144) -> wallet_file (144) Same function
            // / wallet_file_response (145) -> wallet_file_response (145) Same function
            // / wallet_exec (146) -> wallet_exec (146) Same function
            // / wallet_get_subhome (147) -> wallet_get_subhome (147) Same function
            // / wallet_get_subhome_response (148) -> wallet_get_subhome_response (148) Same function
            // / wallet_net_info (149) -> wallet_net_info (149) Same function
            // / wallet_net_info_response (150) -> wallet_net_info_response (150) Same function
            // / wallet_compilance_report (151) -> wallet_compilance_report (151) Same function
            // / wallet_compilance_report_response (152) -> wallet_compilance_report_response (152) Same function
            // / wallet_priv_key (153) -> wallet_priv_key (153) Same function
            // / wallet_priv_key_response (154) -> wallet_priv_key_response (154) Same function
            // / wallet_pub_key (155) -> wallet_pub_key (155) Same function
            // / wallet_pub_key_response (156) -> wallet_pub_key_response (156) Same function
            // / wallet_gen_keys (157) -> wallet_gen_keys (157) Same function
            // / wallet_gen_keys_response (158) -> wallet_gen_keys_response (158) Same function
            // / wallet_sign (159) -> wallet_sign (159) Same function
            // / wallet_sign_response (160) -> wallet_sign_response (160) Same function
            // / wallet_verify (161) -> wallet_verify (161) Same function
            // / wallet_verify_response (162) -> wallet_verify_response (162) Same function
            // / wallet_encrypt (163) -> wallet_encrypt (163) Same function
            // / wallet_encrypt_response (164) -> wallet_encrypt_response (164) Same function
            // / wallet_decrypt (165) -> wallet_decrypt (165) Same function
            // / wallet_decrypt_response (166) -> wallet_decrypt_response (166) Same function
            // / wallet_patch_os (167) -> wallet_patch_os (167) Same function
            // / wallet_patch_os_response (168) -> wallet_patch_os_response (168) Same function
            // / wallet_list_protocols (169) -> wallet_list_protocols (169) Same function
            // / wallet_list_protocols_response (170) -> wallet_list_protocols_response (170) Same function
            // / wallet_trade (171) -> wallet_trade (171) Same function
            // / wallet_trade_response (172) -> wallet_trade_response (172) Same function
            // / wallet_list_trades (173) -> wallet_list_trades (173) Same function
            // / wallet_list_trades_response (174) -> wallet_list_trades_response (174) Same function
            // / wallet_kill_trade (175) -> wallet_kill_trade (175) Same function
            // / wallet_kill_trade_response (176) -> wallet_kill_trade_response (176) Same function
            // / wallet_exec_trade (177) -> wallet_exec_trade (177) Same function
            // / wallet_qr (178) -> wallet_qr (178) Same function
            // / wallet_qr_response (179) -> wallet_qr_response (179) Same function
            // / wallet_bookmark_add (180) -> wallet_bookmark_add (180) Same function
            // / wallet_bookmark_add_response (181) -> wallet_bookmark_add_response (181) Same function
            // / wallet_bookmark_delete (182) -> wallet_bookmark_delete (182) Same function
            // / wallet_bookmark_delete_response (183) -> wallet_bookmark_delete_response (183) Same function
            // / wallet_bookmark_list (184) -> wallet_bookmark_list (184) Same function
            // / wallet_bookmark_list_response (185) -> wallet_bookmark_list_response (185) Same function
            // / wallet_timeseries_list (186) -> wallet_timeseries_list (186) Same function
            // / wallet_timeseries_list_response (187) -> wallet_timeseries_list_response (187) Same function
            // / wallet_timeseries_show (188) -> wallet_timeseries_show (188) Same function
            // / wallet_timeseries_show_response (189) -> wallet_timeseries_show_response (189) Same function
            // / wallet_timeseries_new (190) -> wallet_timeseries_new (190) Same function
            // / wallet_timeseries_new_response (191) -> wallet_timeseries_new_response (191) Same function
            // / wallet_timeseries_add (192) -> wallet_timeseries_add (192) Same function
            // / wallet_timeseries_add_response (193) -> wallet_timeseries_add_response (193) Same function
            // / wallet_r2r_index_hdr (194) -> wallet_r2r_index_hdr (194) Same function
            // / wallet_r2r_index_hdr_response (195) -> wallet_r2r_index_hdr_response (195) Same function
            // / wallet_r2r_bookmarks (196) -> wallet_r2r_bookmarks (196) Same function
            // / wallet_r2r_bookmarks_response (197) -> wallet_r2r_bookmarks_response (197) Same function
            // / wallet_r2r_index (198) -> wallet_r2r_index (198) Same function
            // / wallet_r2r_index_response (199) -> wallet_r2r_index_response (199) Same function
            db.put(Integer.valueOf(200), Integer.valueOf(-1)); // - wallet_cert_create (200) ->  (-1) Removed function
            db.put(Integer.valueOf(201), Integer.valueOf(-1)); // - wallet_cert_create_response (201) ->  (-1) Removed function
            db.put(Integer.valueOf(202), Integer.valueOf(-1)); // - wallet_cert_import (202) ->  (-1) Removed function
            db.put(Integer.valueOf(203), Integer.valueOf(-1)); // - wallet_cert_import_response (203) ->  (-1) Removed function
            db.put(Integer.valueOf(204), Integer.valueOf(-1)); // - wallet_cert_list (204) ->  (-1) Removed function
            db.put(Integer.valueOf(205), Integer.valueOf(-1)); // - wallet_cert_list_response (205) ->  (-1) Removed function
            db.put(Integer.valueOf(206), Integer.valueOf(-1)); // - wallet_cert_get (206) ->  (-1) Removed function
            db.put(Integer.valueOf(207), Integer.valueOf(-1)); // - wallet_cert_get_response (207) ->  (-1) Removed function
            db.put(Integer.valueOf(208), Integer.valueOf(-1)); // - wallet_cert_show (208) ->  (-1) Removed function
            db.put(Integer.valueOf(209), Integer.valueOf(-1)); // - wallet_cert_show_response (209) ->  (-1) Removed function
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
   }

    public void from_prev(svc_t svc) {
        Integer i = db01.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    public void to_prev(svc_t svc) {
        Integer i = db10.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    HashMap<Integer, Integer> db01 = new HashMap<Integer, Integer>();
    HashMap<Integer, Integer> db10 = new HashMap<Integer, Integer>();

}

