//===-                           P L E B B L E
//===-                         https://plebble.us
//===-
//===-              Copyright (C) 2017-2022 root1m3@plebble.us
//===-
//===-                      GNU GENERAL PUBLIC LICENSE
//===-                       Version 3, 29 June 2007
//===-
//===-    This program is free software: you can redistribute it and/or modify
//===-    it under the terms of the GPLv3 License as published by the Free
//===-    Software Foundation.
//===-
//===-    This program is distributed in the hope that it will be useful,
//===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
//===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//===-
//===-    You should have received a copy of the General Public License
//===-    along with this program, see LICENCE file.
//===-    see https://www.gnu.org/licenses
//===-
//===----------------------------------------------------------------------------
//===-
package us.wallet.engine;
import us.CFG;                                                                                 // CFG
import static java.util.Map.entry;                                                             // entry
import java.util.HashMap;                                                                      // HashMap
import static us.gov.socket.types.*;                                                           // *
import java.util.Map;                                                                          // Map

public class svcfish_t {

    static void log(final String line) {                        //--strip
        CFG.log_gov("svcfish_t: " + line);                      //--strip
    }                                                           //--strip

    public svcfish_t() {
        {
            HashMap<Integer, Integer> db = db01;
            //#include <us/api/generated/gov/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_from_prev_v>
            // / socket_error (1) -> socket_error (1) Same function
            // / socket_ping (2) -> socket_ping (2) Same function
            // / socket_ping_response (3) -> socket_ping_response (3) Same function
            // / socket_finished (4) -> socket_finished (4) Same function
            // / id_request (5) -> id_request (5) Same function
            // / id_peer_challenge (6) -> id_peer_challenge (6) Same function
            db.put(Integer.valueOf(8), Integer.valueOf(7)); // ! id_challenge2_response (8) -> id_challenge2_response (7) svc changed
            db.put(Integer.valueOf(9), Integer.valueOf(8)); // ! id_verification_result (9) -> id_verification_result (8) svc changed
            db.put(Integer.valueOf(10), Integer.valueOf(9)); // ! auth_f1 (10) -> auth_f1 (9) svc changed
            db.put(Integer.valueOf(11), Integer.valueOf(10)); // ! peer_f1 (11) -> peer_f1 (10) svc changed
            db.put(Integer.valueOf(12), Integer.valueOf(11)); // ! relay_push (12) -> relay_push (11) svc changed
            db.put(Integer.valueOf(13), Integer.valueOf(12)); // ! dfs_file_request (13) -> dfs_file_request (12) svc changed
            db.put(Integer.valueOf(14), Integer.valueOf(13)); // ! dfs_file_request_ret (14) -> dfs_file_request_ret (13) svc changed
            db.put(Integer.valueOf(15), Integer.valueOf(14)); // ! engine_local_deltas (15) -> engine_local_deltas (14) svc changed
            db.put(Integer.valueOf(16), Integer.valueOf(15)); // ! engine_vote_tip (16) -> engine_vote_tip (15) svc changed
            db.put(Integer.valueOf(17), Integer.valueOf(16)); // ! engine_query_block (17) -> engine_query_block (16) svc changed
            db.put(Integer.valueOf(18), Integer.valueOf(17)); // ! engine_query_block_ret (18) -> engine_query_block_ret (17) svc changed
            db.put(Integer.valueOf(19), Integer.valueOf(18)); // ! engine_sysop (19) -> engine_sysop (18) svc changed
            db.put(Integer.valueOf(20), Integer.valueOf(19)); // ! engine_sysop_ret (20) -> engine_sysop_ret (19) svc changed
            db.put(Integer.valueOf(21), Integer.valueOf(20)); // ! engine_track (21) -> engine_track (20) svc changed
            db.put(Integer.valueOf(22), Integer.valueOf(21)); // ! engine_track_ret (22) -> engine_track_ret (21) svc changed
            db.put(Integer.valueOf(23), Integer.valueOf(22)); // ! engine_ev (23) -> engine_ev (22) svc changed
            db.put(Integer.valueOf(24), Integer.valueOf(23)); // ! engine_ev_track (24) -> engine_ev_track (23) svc changed
            db.put(Integer.valueOf(25), Integer.valueOf(24)); // ! engine_ev_track_ret (25) -> engine_ev_track_ret (24) svc changed
            db.put(Integer.valueOf(26), Integer.valueOf(25)); // ! engine_harvest (26) -> engine_harvest (25) svc changed
            db.put(Integer.valueOf(27), Integer.valueOf(26)); // ! engine_harvest_rollback (27) -> engine_harvest_rollback (26) svc changed
            db.put(Integer.valueOf(28), Integer.valueOf(27)); // ! cash_fetch_accounts (28) -> cash_fetch_accounts (27) svc changed
            db.put(Integer.valueOf(29), Integer.valueOf(28)); // ! cash_fetch_accounts_ret (29) -> cash_fetch_accounts_ret (28) svc changed
            db.put(Integer.valueOf(30), Integer.valueOf(29)); // ! cash_share_file (30) -> cash_share_file (29) svc changed
            db.put(Integer.valueOf(31), Integer.valueOf(30)); // ! cash_share_file_ret (31) -> cash_share_file_ret (30) svc changed
            db.put(Integer.valueOf(32), Integer.valueOf(31)); // ! cash_search_kv (32) -> cash_search_kv (31) svc changed
            db.put(Integer.valueOf(33), Integer.valueOf(32)); // ! cash_search_kv_ret (33) -> cash_search_kv_ret (32) svc changed
            db.put(Integer.valueOf(34), Integer.valueOf(33)); // ! cash_file_hash (34) -> cash_file_hash (33) svc changed
            db.put(Integer.valueOf(35), Integer.valueOf(34)); // ! cash_file_hash_ret (35) -> cash_file_hash_ret (34) svc changed
            db.put(Integer.valueOf(36), Integer.valueOf(35)); // ! cash_file_content (36) -> cash_file_content (35) svc changed
            db.put(Integer.valueOf(37), Integer.valueOf(36)); // ! cash_file_content_ret (37) -> cash_file_content_ret (36) svc changed
            db.put(Integer.valueOf(38), Integer.valueOf(37)); // ! engine_auth_nodes (38) -> engine_auth_nodes (37) svc changed
            db.put(Integer.valueOf(39), Integer.valueOf(38)); // ! engine_auth_nodes_ret (39) -> engine_auth_nodes_ret (38) svc changed
            db.put(Integer.valueOf(40), Integer.valueOf(39)); // ! engine_auth_lookup_node (40) -> engine_auth_lookup_node (39) svc changed
            db.put(Integer.valueOf(41), Integer.valueOf(40)); // ! engine_auth_lookup_node_ret (41) -> engine_auth_lookup_node_ret (40) svc changed
            db.put(Integer.valueOf(42), Integer.valueOf(41)); // ! traders_wallets (42) -> traders_wallets (41) svc changed
            db.put(Integer.valueOf(43), Integer.valueOf(42)); // ! traders_wallets_ret (43) -> traders_wallets_ret (42) svc changed
            db.put(Integer.valueOf(44), Integer.valueOf(43)); // ! traders_lookup_wallet (44) -> traders_lookup_wallet (43) svc changed
            db.put(Integer.valueOf(45), Integer.valueOf(44)); // ! traders_lookup_wallet_ret (45) -> traders_lookup_wallet_ret (44) svc changed
            db.put(Integer.valueOf(46), Integer.valueOf(45)); // ! traders_random_wallet (46) -> traders_random_wallet (45) svc changed
            db.put(Integer.valueOf(47), Integer.valueOf(46)); // ! traders_random_wallet_ret (47) -> traders_random_wallet_ret (46) svc changed
            db.put(Integer.valueOf(48), Integer.valueOf(47)); // ! sys_f1 (48) -> sys_f1 (47) svc changed
            db.put(Integer.valueOf(7), Integer.valueOf(-1)); // - id_challenge_response (7) ->  (-1) svc deleted
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_from_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_from_prev_v>
            db.put(Integer.valueOf(49), Integer.valueOf(48)); // ! engine_print_grid (49) -> engine_print_grid (48) svc changed
            db.put(Integer.valueOf(50), Integer.valueOf(49)); // ! engine_print_grid_ret (50) -> engine_print_grid_ret (49) svc changed
            db.put(Integer.valueOf(51), Integer.valueOf(50)); // ! engine_print_socket_connections (51) -> engine_print_socket_connections (50) svc changed
            db.put(Integer.valueOf(52), Integer.valueOf(51)); // ! engine_print_socket_connections_ret (52) -> engine_print_socket_connections_ret (51) svc changed
            db.put(Integer.valueOf(53), Integer.valueOf(52)); // ! engine_allw (53) -> engine_allw (52) svc changed
            db.put(Integer.valueOf(54), Integer.valueOf(53)); // ! engine_allw_ret (54) -> engine_allw_ret (53) svc changed
            db.put(Integer.valueOf(55), Integer.valueOf(54)); // ! engine_sync (55) -> engine_sync (54) svc changed
            db.put(Integer.valueOf(56), Integer.valueOf(55)); // ! engine_sync_ret (56) -> engine_sync_ret (55) svc changed
            db.put(Integer.valueOf(57), Integer.valueOf(56)); // ! engine_reload_file (57) -> engine_reload_file (56) svc changed
            db.put(Integer.valueOf(58), Integer.valueOf(57)); // ! engine_reload_file_ret (58) -> engine_reload_file_ret (57) svc changed
            db.put(Integer.valueOf(59), Integer.valueOf(58)); // ! engine_get_component_update (59) -> engine_get_component_update (58) svc changed
            db.put(Integer.valueOf(60), Integer.valueOf(59)); // ! engine_get_component_update_ret (60) -> engine_get_component_update_ret (59) svc changed
            db.put(Integer.valueOf(61), Integer.valueOf(60)); // ! engine_get_component_hash (61) -> engine_get_component_hash (60) svc changed
            db.put(Integer.valueOf(62), Integer.valueOf(61)); // ! engine_get_component_hash_ret (62) -> engine_get_component_hash_ret (61) svc changed
            db.put(Integer.valueOf(63), Integer.valueOf(62)); // ! engine_harvest (63) -> engine_harvest (62) svc changed
            db.put(Integer.valueOf(64), Integer.valueOf(63)); // ! engine_harvest_ret (64) -> engine_harvest_ret (63) svc changed
            db.put(Integer.valueOf(65), Integer.valueOf(64)); // ! engine_world (65) -> engine_world (64) svc changed
            db.put(Integer.valueOf(66), Integer.valueOf(65)); // ! engine_world_ret (66) -> engine_world_ret (65) svc changed
            db.put(Integer.valueOf(67), Integer.valueOf(66)); // ! engine_lookup_wallet (67) -> engine_lookup_wallet (66) svc changed
            db.put(Integer.valueOf(68), Integer.valueOf(67)); // ! engine_lookup_wallet_ret (68) -> engine_lookup_wallet_ret (67) svc changed
            db.put(Integer.valueOf(69), Integer.valueOf(68)); // ! engine_random_wallet (69) -> engine_random_wallet (68) svc changed
            db.put(Integer.valueOf(70), Integer.valueOf(69)); // ! engine_random_wallet_ret (70) -> engine_random_wallet_ret (69) svc changed
            db.put(Integer.valueOf(71), Integer.valueOf(70)); // ! engine_register_w (71) -> engine_register_w (70) svc changed
            db.put(Integer.valueOf(72), Integer.valueOf(71)); // ! engine_register_w_ret (72) -> engine_register_w_ret (71) svc changed
            db.put(Integer.valueOf(73), Integer.valueOf(72)); // ! engine_conf (73) -> engine_conf (72) svc changed
            db.put(Integer.valueOf(74), Integer.valueOf(73)); // ! engine_conf_ret (74) -> engine_conf_ret (73) svc changed
            db.put(Integer.valueOf(75), Integer.valueOf(74)); // ! pairing_pair_device (75) -> pairing_pair_device (74) svc changed
            db.put(Integer.valueOf(76), Integer.valueOf(75)); // ! pairing_pair_device_ret (76) -> pairing_pair_device_ret (75) svc changed
            db.put(Integer.valueOf(77), Integer.valueOf(76)); // ! pairing_unpair_device (77) -> pairing_unpair_device (76) svc changed
            db.put(Integer.valueOf(78), Integer.valueOf(77)); // ! pairing_unpair_device_ret (78) -> pairing_unpair_device_ret (77) svc changed
            db.put(Integer.valueOf(79), Integer.valueOf(78)); // ! pairing_list_devices (79) -> pairing_list_devices (78) svc changed
            db.put(Integer.valueOf(80), Integer.valueOf(79)); // ! pairing_list_devices_ret (80) -> pairing_list_devices_ret (79) svc changed
            db.put(Integer.valueOf(81), Integer.valueOf(80)); // ! pairing_attempts (81) -> pairing_attempts (80) svc changed
            db.put(Integer.valueOf(82), Integer.valueOf(81)); // ! pairing_attempts_ret (82) -> pairing_attempts_ret (81) svc changed
            db.put(Integer.valueOf(83), Integer.valueOf(82)); // ! pairing_prepair_device (83) -> pairing_prepair_device (82) svc changed
            db.put(Integer.valueOf(84), Integer.valueOf(83)); // ! pairing_prepair_device_ret (84) -> pairing_prepair_device_ret (83) svc changed
            db.put(Integer.valueOf(85), Integer.valueOf(84)); // ! pairing_unprepair_device (85) -> pairing_unprepair_device (84) svc changed
            db.put(Integer.valueOf(86), Integer.valueOf(85)); // ! pairing_unprepair_device_ret (86) -> pairing_unprepair_device_ret (85) svc changed
            db.put(Integer.valueOf(87), Integer.valueOf(86)); // ! r2r_trading_msg (87) -> r2r_trading_msg (86) svc changed
            db.put(Integer.valueOf(88), Integer.valueOf(87)); // ! wallet_balance (88) -> wallet_balance (87) svc changed
            db.put(Integer.valueOf(89), Integer.valueOf(88)); // ! wallet_balance_ret (89) -> wallet_balance_ret (88) svc changed
            db.put(Integer.valueOf(90), Integer.valueOf(89)); // ! wallet_list (90) -> wallet_list (89) svc changed
            db.put(Integer.valueOf(91), Integer.valueOf(90)); // ! wallet_list_ret (91) -> wallet_list_ret (90) svc changed
            db.put(Integer.valueOf(92), Integer.valueOf(91)); // ! wallet_recv_address (92) -> wallet_recv_address (91) svc changed
            db.put(Integer.valueOf(93), Integer.valueOf(92)); // ! wallet_recv_address_ret (93) -> wallet_recv_address_ret (92) svc changed
            db.put(Integer.valueOf(94), Integer.valueOf(93)); // ! wallet_new_address (94) -> wallet_new_address (93) svc changed
            db.put(Integer.valueOf(95), Integer.valueOf(94)); // ! wallet_new_address_ret (95) -> wallet_new_address_ret (94) svc changed
            db.put(Integer.valueOf(96), Integer.valueOf(95)); // ! wallet_add_address (96) -> wallet_add_address (95) svc changed
            db.put(Integer.valueOf(97), Integer.valueOf(96)); // ! wallet_add_address_ret (97) -> wallet_add_address_ret (96) svc changed
            db.put(Integer.valueOf(98), Integer.valueOf(97)); // ! wallet_transfer (98) -> wallet_transfer (97) svc changed
            db.put(Integer.valueOf(99), Integer.valueOf(98)); // ! wallet_transfer_ret (99) -> wallet_transfer_ret (98) svc changed
            db.put(Integer.valueOf(100), Integer.valueOf(99)); // ! wallet_transfer_from (100) -> wallet_transfer_from (99) svc changed
            db.put(Integer.valueOf(101), Integer.valueOf(100)); // ! wallet_transfer_from_ret (101) -> wallet_transfer_from_ret (100) svc changed
            db.put(Integer.valueOf(102), Integer.valueOf(101)); // ! wallet_tx_charge_pay (102) -> wallet_tx_charge_pay (101) svc changed
            db.put(Integer.valueOf(103), Integer.valueOf(102)); // ! wallet_tx_charge_pay_ret (103) -> wallet_tx_charge_pay_ret (102) svc changed
            db.put(Integer.valueOf(104), Integer.valueOf(103)); // ! wallet_invoice_verify (104) -> wallet_invoice_verify (103) svc changed
            db.put(Integer.valueOf(105), Integer.valueOf(104)); // ! wallet_invoice_verify_ret (105) -> wallet_invoice_verify_ret (104) svc changed
            db.put(Integer.valueOf(106), Integer.valueOf(105)); // ! wallet_payment_verify (106) -> wallet_payment_verify (105) svc changed
            db.put(Integer.valueOf(107), Integer.valueOf(106)); // ! wallet_payment_verify_ret (107) -> wallet_payment_verify_ret (106) svc changed
            db.put(Integer.valueOf(108), Integer.valueOf(107)); // ! wallet_tx_pay (108) -> wallet_tx_pay (107) svc changed
            db.put(Integer.valueOf(109), Integer.valueOf(108)); // ! wallet_tx_pay_ret (109) -> wallet_tx_pay_ret (108) svc changed
            db.put(Integer.valueOf(110), Integer.valueOf(109)); // ! wallet_tx_new (110) -> wallet_tx_new (109) svc changed
            db.put(Integer.valueOf(111), Integer.valueOf(110)); // ! wallet_tx_new_ret (111) -> wallet_tx_new_ret (110) svc changed
            db.put(Integer.valueOf(112), Integer.valueOf(111)); // ! wallet_tx_add_section (112) -> wallet_tx_add_section (111) svc changed
            db.put(Integer.valueOf(113), Integer.valueOf(112)); // ! wallet_tx_add_section_ret (113) -> wallet_tx_add_section_ret (112) svc changed
            db.put(Integer.valueOf(114), Integer.valueOf(113)); // ! wallet_tx_add_input (114) -> wallet_tx_add_input (113) svc changed
            db.put(Integer.valueOf(115), Integer.valueOf(114)); // ! wallet_tx_add_input_ret (115) -> wallet_tx_add_input_ret (114) svc changed
            db.put(Integer.valueOf(116), Integer.valueOf(115)); // ! wallet_tx_add_output (116) -> wallet_tx_add_output (115) svc changed
            db.put(Integer.valueOf(117), Integer.valueOf(116)); // ! wallet_tx_add_output_ret (117) -> wallet_tx_add_output_ret (116) svc changed
            db.put(Integer.valueOf(118), Integer.valueOf(117)); // ! wallet_tx_sign (118) -> wallet_tx_sign (117) svc changed
            db.put(Integer.valueOf(119), Integer.valueOf(118)); // ! wallet_tx_sign_ret (119) -> wallet_tx_sign_ret (118) svc changed
            db.put(Integer.valueOf(120), Integer.valueOf(119)); // ! wallet_tx_send (120) -> wallet_tx_send (119) svc changed
            db.put(Integer.valueOf(121), Integer.valueOf(120)); // ! wallet_tx_send_ret (121) -> wallet_tx_send_ret (120) svc changed
            db.put(Integer.valueOf(122), Integer.valueOf(121)); // ! wallet_tx_decode (122) -> wallet_tx_decode (121) svc changed
            db.put(Integer.valueOf(123), Integer.valueOf(122)); // ! wallet_tx_decode_ret (123) -> wallet_tx_decode_ret (122) svc changed
            db.put(Integer.valueOf(124), Integer.valueOf(123)); // ! wallet_tx_check (124) -> wallet_tx_check (123) svc changed
            db.put(Integer.valueOf(125), Integer.valueOf(124)); // ! wallet_tx_check_ret (125) -> wallet_tx_check_ret (124) svc changed
            db.put(Integer.valueOf(126), Integer.valueOf(125)); // ! wallet_set_supply (126) -> wallet_set_supply (125) svc changed
            db.put(Integer.valueOf(127), Integer.valueOf(126)); // ! wallet_set_supply_ret (127) -> wallet_set_supply_ret (126) svc changed
            db.put(Integer.valueOf(128), Integer.valueOf(127)); // ! wallet_store_kv (128) -> wallet_store_kv (127) svc changed
            db.put(Integer.valueOf(129), Integer.valueOf(128)); // ! wallet_store_kv_ret (129) -> wallet_store_kv_ret (128) svc changed
            db.put(Integer.valueOf(130), Integer.valueOf(129)); // ! wallet_rm_kv (130) -> wallet_rm_kv (129) svc changed
            db.put(Integer.valueOf(131), Integer.valueOf(130)); // ! wallet_rm_kv_ret (131) -> wallet_rm_kv_ret (130) svc changed
            db.put(Integer.valueOf(132), Integer.valueOf(131)); // ! wallet_store_file (132) -> wallet_store_file (131) svc changed
            db.put(Integer.valueOf(133), Integer.valueOf(132)); // ! wallet_store_file_ret (133) -> wallet_store_file_ret (132) svc changed
            db.put(Integer.valueOf(134), Integer.valueOf(133)); // ! wallet_rm_file (134) -> wallet_rm_file (133) svc changed
            db.put(Integer.valueOf(135), Integer.valueOf(134)); // ! wallet_rm_file_ret (135) -> wallet_rm_file_ret (134) svc changed
            db.put(Integer.valueOf(136), Integer.valueOf(135)); // ! wallet_search (136) -> wallet_search (135) svc changed
            db.put(Integer.valueOf(137), Integer.valueOf(136)); // ! wallet_search_ret (137) -> wallet_search_ret (136) svc changed
            db.put(Integer.valueOf(138), Integer.valueOf(137)); // ! wallet_file (138) -> wallet_file (137) svc changed
            db.put(Integer.valueOf(139), Integer.valueOf(138)); // ! wallet_file_ret (139) -> wallet_file_ret (138) svc changed
            db.put(Integer.valueOf(140), Integer.valueOf(139)); // ! wallet_exec (140) -> wallet_exec (139) svc changed
            db.put(Integer.valueOf(141), Integer.valueOf(140)); // ! wallet_get_subhome (141) -> wallet_get_subhome (140) svc changed
            db.put(Integer.valueOf(142), Integer.valueOf(141)); // ! wallet_get_subhome_ret (142) -> wallet_get_subhome_ret (141) svc changed
            db.put(Integer.valueOf(143), Integer.valueOf(142)); // ! wallet_net_info (143) -> wallet_net_info (142) svc changed
            db.put(Integer.valueOf(144), Integer.valueOf(143)); // ! wallet_net_info_ret (144) -> wallet_net_info_ret (143) svc changed
            db.put(Integer.valueOf(145), Integer.valueOf(144)); // ! wallet_compilance_report (145) -> wallet_compilance_report (144) svc changed
            db.put(Integer.valueOf(146), Integer.valueOf(145)); // ! wallet_compilance_report_ret (146) -> wallet_compilance_report_ret (145) svc changed
            db.put(Integer.valueOf(147), Integer.valueOf(146)); // ! wallet_priv_key (147) -> wallet_priv_key (146) svc changed
            db.put(Integer.valueOf(148), Integer.valueOf(147)); // ! wallet_priv_key_ret (148) -> wallet_priv_key_ret (147) svc changed
            db.put(Integer.valueOf(149), Integer.valueOf(148)); // ! wallet_pub_key (149) -> wallet_pub_key (148) svc changed
            db.put(Integer.valueOf(150), Integer.valueOf(149)); // ! wallet_pub_key_ret (150) -> wallet_pub_key_ret (149) svc changed
            db.put(Integer.valueOf(151), Integer.valueOf(150)); // ! wallet_gen_keys (151) -> wallet_gen_keys (150) svc changed
            db.put(Integer.valueOf(152), Integer.valueOf(151)); // ! wallet_gen_keys_ret (152) -> wallet_gen_keys_ret (151) svc changed
            db.put(Integer.valueOf(153), Integer.valueOf(152)); // ! wallet_sign (153) -> wallet_sign (152) svc changed
            db.put(Integer.valueOf(154), Integer.valueOf(153)); // ! wallet_sign_ret (154) -> wallet_sign_ret (153) svc changed
            db.put(Integer.valueOf(155), Integer.valueOf(154)); // ! wallet_verify (155) -> wallet_verify (154) svc changed
            db.put(Integer.valueOf(156), Integer.valueOf(155)); // ! wallet_verify_ret (156) -> wallet_verify_ret (155) svc changed
            db.put(Integer.valueOf(157), Integer.valueOf(156)); // ! wallet_encrypt (157) -> wallet_encrypt (156) svc changed
            db.put(Integer.valueOf(158), Integer.valueOf(157)); // ! wallet_encrypt_ret (158) -> wallet_encrypt_ret (157) svc changed
            db.put(Integer.valueOf(159), Integer.valueOf(158)); // ! wallet_decrypt (159) -> wallet_decrypt (158) svc changed
            db.put(Integer.valueOf(160), Integer.valueOf(159)); // ! wallet_decrypt_ret (160) -> wallet_decrypt_ret (159) svc changed
            db.put(Integer.valueOf(161), Integer.valueOf(160)); // ! wallet_patch_os (161) -> wallet_patch_os (160) svc changed
            db.put(Integer.valueOf(162), Integer.valueOf(161)); // ! wallet_patch_os_ret (162) -> wallet_patch_os_ret (161) svc changed
            db.put(Integer.valueOf(163), Integer.valueOf(162)); // ! wallet_list_protocols (163) -> wallet_list_protocols (162) svc changed
            db.put(Integer.valueOf(164), Integer.valueOf(163)); // ! wallet_list_protocols_ret (164) -> wallet_list_protocols_ret (163) svc changed
            db.put(Integer.valueOf(165), Integer.valueOf(164)); // ! wallet_trade (165) -> wallet_trade (164) svc changed
            db.put(Integer.valueOf(166), Integer.valueOf(165)); // ! wallet_trade_ret (166) -> wallet_trade_ret (165) svc changed
            db.put(Integer.valueOf(167), Integer.valueOf(166)); // ! wallet_list_trades (167) -> wallet_list_trades (166) svc changed
            db.put(Integer.valueOf(168), Integer.valueOf(167)); // ! wallet_list_trades_ret (168) -> wallet_list_trades_ret (167) svc changed
            db.put(Integer.valueOf(169), Integer.valueOf(168)); // ! wallet_kill_trade (169) -> wallet_kill_trade (168) svc changed
            db.put(Integer.valueOf(170), Integer.valueOf(169)); // ! wallet_kill_trade_ret (170) -> wallet_kill_trade_ret (169) svc changed
            db.put(Integer.valueOf(171), Integer.valueOf(170)); // ! wallet_exec_trade (171) -> wallet_exec_trade (170) svc changed
            db.put(Integer.valueOf(172), Integer.valueOf(171)); // ! wallet_qr (172) -> wallet_qr (171) svc changed
            db.put(Integer.valueOf(173), Integer.valueOf(172)); // ! wallet_qr_ret (173) -> wallet_qr_ret (172) svc changed
            db.put(Integer.valueOf(174), Integer.valueOf(173)); // ! wallet_bookmark_add (174) -> wallet_bookmark_add (173) svc changed
            db.put(Integer.valueOf(175), Integer.valueOf(174)); // ! wallet_bookmark_add_ret (175) -> wallet_bookmark_add_ret (174) svc changed
            db.put(Integer.valueOf(176), Integer.valueOf(175)); // ! wallet_bookmark_delete (176) -> wallet_bookmark_delete (175) svc changed
            db.put(Integer.valueOf(177), Integer.valueOf(176)); // ! wallet_bookmark_delete_ret (177) -> wallet_bookmark_delete_ret (176) svc changed
            db.put(Integer.valueOf(178), Integer.valueOf(177)); // ! wallet_bookmark_list (178) -> wallet_bookmark_list (177) svc changed
            db.put(Integer.valueOf(179), Integer.valueOf(178)); // ! wallet_bookmark_list_ret (179) -> wallet_bookmark_list_ret (178) svc changed
            db.put(Integer.valueOf(180), Integer.valueOf(179)); // ! wallet_timeseries_list (180) -> wallet_timeseries_list (179) svc changed
            db.put(Integer.valueOf(181), Integer.valueOf(180)); // ! wallet_timeseries_list_ret (181) -> wallet_timeseries_list_ret (180) svc changed
            db.put(Integer.valueOf(182), Integer.valueOf(181)); // ! wallet_timeseries_show (182) -> wallet_timeseries_show (181) svc changed
            db.put(Integer.valueOf(183), Integer.valueOf(182)); // ! wallet_timeseries_show_ret (183) -> wallet_timeseries_show_ret (182) svc changed
            db.put(Integer.valueOf(184), Integer.valueOf(183)); // ! wallet_timeseries_new (184) -> wallet_timeseries_new (183) svc changed
            db.put(Integer.valueOf(185), Integer.valueOf(184)); // ! wallet_timeseries_new_ret (185) -> wallet_timeseries_new_ret (184) svc changed
            db.put(Integer.valueOf(186), Integer.valueOf(185)); // ! wallet_timeseries_add (186) -> wallet_timeseries_add (185) svc changed
            db.put(Integer.valueOf(187), Integer.valueOf(186)); // ! wallet_timeseries_add_ret (187) -> wallet_timeseries_add_ret (186) svc changed
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
        {
            HashMap<Integer, Integer> db = db10;
            //#include <us/api/generated/gov/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/gov/java/svc_to_prev_v>
            // / socket_error (1) -> socket_error (1) Same function
            // / socket_ping (2) -> socket_ping (2) Same function
            // / socket_ping_response (3) -> socket_ping_response (3) Same function
            // / socket_finished (4) -> socket_finished (4) Same function
            // / id_request (5) -> id_request (5) Same function
            // / id_peer_challenge (6) -> id_peer_challenge (6) Same function
            db.put(Integer.valueOf(7), Integer.valueOf(8)); // ! id_challenge2_response (7) -> id_challenge2_response (8) svc changed
            db.put(Integer.valueOf(8), Integer.valueOf(9)); // ! id_verification_result (8) -> id_verification_result (9) svc changed
            db.put(Integer.valueOf(9), Integer.valueOf(10)); // ! auth_f1 (9) -> auth_f1 (10) svc changed
            db.put(Integer.valueOf(10), Integer.valueOf(11)); // ! peer_f1 (10) -> peer_f1 (11) svc changed
            db.put(Integer.valueOf(11), Integer.valueOf(12)); // ! relay_push (11) -> relay_push (12) svc changed
            db.put(Integer.valueOf(12), Integer.valueOf(13)); // ! dfs_file_request (12) -> dfs_file_request (13) svc changed
            db.put(Integer.valueOf(13), Integer.valueOf(14)); // ! dfs_file_request_ret (13) -> dfs_file_request_ret (14) svc changed
            db.put(Integer.valueOf(14), Integer.valueOf(15)); // ! engine_local_deltas (14) -> engine_local_deltas (15) svc changed
            db.put(Integer.valueOf(15), Integer.valueOf(16)); // ! engine_vote_tip (15) -> engine_vote_tip (16) svc changed
            db.put(Integer.valueOf(16), Integer.valueOf(17)); // ! engine_query_block (16) -> engine_query_block (17) svc changed
            db.put(Integer.valueOf(17), Integer.valueOf(18)); // ! engine_query_block_ret (17) -> engine_query_block_ret (18) svc changed
            db.put(Integer.valueOf(18), Integer.valueOf(19)); // ! engine_sysop (18) -> engine_sysop (19) svc changed
            db.put(Integer.valueOf(19), Integer.valueOf(20)); // ! engine_sysop_ret (19) -> engine_sysop_ret (20) svc changed
            db.put(Integer.valueOf(20), Integer.valueOf(21)); // ! engine_track (20) -> engine_track (21) svc changed
            db.put(Integer.valueOf(21), Integer.valueOf(22)); // ! engine_track_ret (21) -> engine_track_ret (22) svc changed
            db.put(Integer.valueOf(22), Integer.valueOf(23)); // ! engine_ev (22) -> engine_ev (23) svc changed
            db.put(Integer.valueOf(23), Integer.valueOf(24)); // ! engine_ev_track (23) -> engine_ev_track (24) svc changed
            db.put(Integer.valueOf(24), Integer.valueOf(25)); // ! engine_ev_track_ret (24) -> engine_ev_track_ret (25) svc changed
            db.put(Integer.valueOf(25), Integer.valueOf(26)); // ! engine_harvest (25) -> engine_harvest (26) svc changed
            db.put(Integer.valueOf(26), Integer.valueOf(27)); // ! engine_harvest_rollback (26) -> engine_harvest_rollback (27) svc changed
            db.put(Integer.valueOf(27), Integer.valueOf(28)); // ! cash_fetch_accounts (27) -> cash_fetch_accounts (28) svc changed
            db.put(Integer.valueOf(28), Integer.valueOf(29)); // ! cash_fetch_accounts_ret (28) -> cash_fetch_accounts_ret (29) svc changed
            db.put(Integer.valueOf(29), Integer.valueOf(30)); // ! cash_share_file (29) -> cash_share_file (30) svc changed
            db.put(Integer.valueOf(30), Integer.valueOf(31)); // ! cash_share_file_ret (30) -> cash_share_file_ret (31) svc changed
            db.put(Integer.valueOf(31), Integer.valueOf(32)); // ! cash_search_kv (31) -> cash_search_kv (32) svc changed
            db.put(Integer.valueOf(32), Integer.valueOf(33)); // ! cash_search_kv_ret (32) -> cash_search_kv_ret (33) svc changed
            db.put(Integer.valueOf(33), Integer.valueOf(34)); // ! cash_file_hash (33) -> cash_file_hash (34) svc changed
            db.put(Integer.valueOf(34), Integer.valueOf(35)); // ! cash_file_hash_ret (34) -> cash_file_hash_ret (35) svc changed
            db.put(Integer.valueOf(35), Integer.valueOf(36)); // ! cash_file_content (35) -> cash_file_content (36) svc changed
            db.put(Integer.valueOf(36), Integer.valueOf(37)); // ! cash_file_content_ret (36) -> cash_file_content_ret (37) svc changed
            db.put(Integer.valueOf(37), Integer.valueOf(38)); // ! engine_auth_nodes (37) -> engine_auth_nodes (38) svc changed
            db.put(Integer.valueOf(38), Integer.valueOf(39)); // ! engine_auth_nodes_ret (38) -> engine_auth_nodes_ret (39) svc changed
            db.put(Integer.valueOf(39), Integer.valueOf(40)); // ! engine_auth_lookup_node (39) -> engine_auth_lookup_node (40) svc changed
            db.put(Integer.valueOf(40), Integer.valueOf(41)); // ! engine_auth_lookup_node_ret (40) -> engine_auth_lookup_node_ret (41) svc changed
            db.put(Integer.valueOf(41), Integer.valueOf(42)); // ! traders_wallets (41) -> traders_wallets (42) svc changed
            db.put(Integer.valueOf(42), Integer.valueOf(43)); // ! traders_wallets_ret (42) -> traders_wallets_ret (43) svc changed
            db.put(Integer.valueOf(43), Integer.valueOf(44)); // ! traders_lookup_wallet (43) -> traders_lookup_wallet (44) svc changed
            db.put(Integer.valueOf(44), Integer.valueOf(45)); // ! traders_lookup_wallet_ret (44) -> traders_lookup_wallet_ret (45) svc changed
            db.put(Integer.valueOf(45), Integer.valueOf(46)); // ! traders_random_wallet (45) -> traders_random_wallet (46) svc changed
            db.put(Integer.valueOf(46), Integer.valueOf(47)); // ! traders_random_wallet_ret (46) -> traders_random_wallet_ret (47) svc changed
            db.put(Integer.valueOf(47), Integer.valueOf(48)); // ! sys_f1 (47) -> sys_f1 (48) svc changed
            // /  (-1) -> id_challenge_response (7) wont be called
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
            //#include <us/api/generated/wallet/java/svc_to_prev_v>
            //------------------------------------------------------------__begin__------generated by configure, do not edit.
            //content of file: <us/api/generated/wallet/java/svc_to_prev_v>
            db.put(Integer.valueOf(48), Integer.valueOf(49)); // ! engine_print_grid (48) -> engine_print_grid (49) svc changed
            db.put(Integer.valueOf(49), Integer.valueOf(50)); // ! engine_print_grid_ret (49) -> engine_print_grid_ret (50) svc changed
            db.put(Integer.valueOf(50), Integer.valueOf(51)); // ! engine_print_socket_connections (50) -> engine_print_socket_connections (51) svc changed
            db.put(Integer.valueOf(51), Integer.valueOf(52)); // ! engine_print_socket_connections_ret (51) -> engine_print_socket_connections_ret (52) svc changed
            db.put(Integer.valueOf(52), Integer.valueOf(53)); // ! engine_allw (52) -> engine_allw (53) svc changed
            db.put(Integer.valueOf(53), Integer.valueOf(54)); // ! engine_allw_ret (53) -> engine_allw_ret (54) svc changed
            db.put(Integer.valueOf(54), Integer.valueOf(55)); // ! engine_sync (54) -> engine_sync (55) svc changed
            db.put(Integer.valueOf(55), Integer.valueOf(56)); // ! engine_sync_ret (55) -> engine_sync_ret (56) svc changed
            db.put(Integer.valueOf(56), Integer.valueOf(57)); // ! engine_reload_file (56) -> engine_reload_file (57) svc changed
            db.put(Integer.valueOf(57), Integer.valueOf(58)); // ! engine_reload_file_ret (57) -> engine_reload_file_ret (58) svc changed
            db.put(Integer.valueOf(58), Integer.valueOf(59)); // ! engine_get_component_update (58) -> engine_get_component_update (59) svc changed
            db.put(Integer.valueOf(59), Integer.valueOf(60)); // ! engine_get_component_update_ret (59) -> engine_get_component_update_ret (60) svc changed
            db.put(Integer.valueOf(60), Integer.valueOf(61)); // ! engine_get_component_hash (60) -> engine_get_component_hash (61) svc changed
            db.put(Integer.valueOf(61), Integer.valueOf(62)); // ! engine_get_component_hash_ret (61) -> engine_get_component_hash_ret (62) svc changed
            db.put(Integer.valueOf(62), Integer.valueOf(63)); // ! engine_harvest (62) -> engine_harvest (63) svc changed
            db.put(Integer.valueOf(63), Integer.valueOf(64)); // ! engine_harvest_ret (63) -> engine_harvest_ret (64) svc changed
            db.put(Integer.valueOf(64), Integer.valueOf(65)); // ! engine_world (64) -> engine_world (65) svc changed
            db.put(Integer.valueOf(65), Integer.valueOf(66)); // ! engine_world_ret (65) -> engine_world_ret (66) svc changed
            db.put(Integer.valueOf(66), Integer.valueOf(67)); // ! engine_lookup_wallet (66) -> engine_lookup_wallet (67) svc changed
            db.put(Integer.valueOf(67), Integer.valueOf(68)); // ! engine_lookup_wallet_ret (67) -> engine_lookup_wallet_ret (68) svc changed
            db.put(Integer.valueOf(68), Integer.valueOf(69)); // ! engine_random_wallet (68) -> engine_random_wallet (69) svc changed
            db.put(Integer.valueOf(69), Integer.valueOf(70)); // ! engine_random_wallet_ret (69) -> engine_random_wallet_ret (70) svc changed
            db.put(Integer.valueOf(70), Integer.valueOf(71)); // ! engine_register_w (70) -> engine_register_w (71) svc changed
            db.put(Integer.valueOf(71), Integer.valueOf(72)); // ! engine_register_w_ret (71) -> engine_register_w_ret (72) svc changed
            db.put(Integer.valueOf(72), Integer.valueOf(73)); // ! engine_conf (72) -> engine_conf (73) svc changed
            db.put(Integer.valueOf(73), Integer.valueOf(74)); // ! engine_conf_ret (73) -> engine_conf_ret (74) svc changed
            db.put(Integer.valueOf(74), Integer.valueOf(75)); // ! pairing_pair_device (74) -> pairing_pair_device (75) svc changed
            db.put(Integer.valueOf(75), Integer.valueOf(76)); // ! pairing_pair_device_ret (75) -> pairing_pair_device_ret (76) svc changed
            db.put(Integer.valueOf(76), Integer.valueOf(77)); // ! pairing_unpair_device (76) -> pairing_unpair_device (77) svc changed
            db.put(Integer.valueOf(77), Integer.valueOf(78)); // ! pairing_unpair_device_ret (77) -> pairing_unpair_device_ret (78) svc changed
            db.put(Integer.valueOf(78), Integer.valueOf(79)); // ! pairing_list_devices (78) -> pairing_list_devices (79) svc changed
            db.put(Integer.valueOf(79), Integer.valueOf(80)); // ! pairing_list_devices_ret (79) -> pairing_list_devices_ret (80) svc changed
            db.put(Integer.valueOf(80), Integer.valueOf(81)); // ! pairing_attempts (80) -> pairing_attempts (81) svc changed
            db.put(Integer.valueOf(81), Integer.valueOf(82)); // ! pairing_attempts_ret (81) -> pairing_attempts_ret (82) svc changed
            db.put(Integer.valueOf(82), Integer.valueOf(83)); // ! pairing_prepair_device (82) -> pairing_prepair_device (83) svc changed
            db.put(Integer.valueOf(83), Integer.valueOf(84)); // ! pairing_prepair_device_ret (83) -> pairing_prepair_device_ret (84) svc changed
            db.put(Integer.valueOf(84), Integer.valueOf(85)); // ! pairing_unprepair_device (84) -> pairing_unprepair_device (85) svc changed
            db.put(Integer.valueOf(85), Integer.valueOf(86)); // ! pairing_unprepair_device_ret (85) -> pairing_unprepair_device_ret (86) svc changed
            db.put(Integer.valueOf(86), Integer.valueOf(87)); // ! r2r_trading_msg (86) -> r2r_trading_msg (87) svc changed
            db.put(Integer.valueOf(87), Integer.valueOf(88)); // ! wallet_balance (87) -> wallet_balance (88) svc changed
            db.put(Integer.valueOf(88), Integer.valueOf(89)); // ! wallet_balance_ret (88) -> wallet_balance_ret (89) svc changed
            db.put(Integer.valueOf(89), Integer.valueOf(90)); // ! wallet_list (89) -> wallet_list (90) svc changed
            db.put(Integer.valueOf(90), Integer.valueOf(91)); // ! wallet_list_ret (90) -> wallet_list_ret (91) svc changed
            db.put(Integer.valueOf(91), Integer.valueOf(92)); // ! wallet_recv_address (91) -> wallet_recv_address (92) svc changed
            db.put(Integer.valueOf(92), Integer.valueOf(93)); // ! wallet_recv_address_ret (92) -> wallet_recv_address_ret (93) svc changed
            db.put(Integer.valueOf(93), Integer.valueOf(94)); // ! wallet_new_address (93) -> wallet_new_address (94) svc changed
            db.put(Integer.valueOf(94), Integer.valueOf(95)); // ! wallet_new_address_ret (94) -> wallet_new_address_ret (95) svc changed
            db.put(Integer.valueOf(95), Integer.valueOf(96)); // ! wallet_add_address (95) -> wallet_add_address (96) svc changed
            db.put(Integer.valueOf(96), Integer.valueOf(97)); // ! wallet_add_address_ret (96) -> wallet_add_address_ret (97) svc changed
            db.put(Integer.valueOf(97), Integer.valueOf(98)); // ! wallet_transfer (97) -> wallet_transfer (98) svc changed
            db.put(Integer.valueOf(98), Integer.valueOf(99)); // ! wallet_transfer_ret (98) -> wallet_transfer_ret (99) svc changed
            db.put(Integer.valueOf(99), Integer.valueOf(100)); // ! wallet_transfer_from (99) -> wallet_transfer_from (100) svc changed
            db.put(Integer.valueOf(100), Integer.valueOf(101)); // ! wallet_transfer_from_ret (100) -> wallet_transfer_from_ret (101) svc changed
            db.put(Integer.valueOf(101), Integer.valueOf(102)); // ! wallet_tx_charge_pay (101) -> wallet_tx_charge_pay (102) svc changed
            db.put(Integer.valueOf(102), Integer.valueOf(103)); // ! wallet_tx_charge_pay_ret (102) -> wallet_tx_charge_pay_ret (103) svc changed
            db.put(Integer.valueOf(103), Integer.valueOf(104)); // ! wallet_invoice_verify (103) -> wallet_invoice_verify (104) svc changed
            db.put(Integer.valueOf(104), Integer.valueOf(105)); // ! wallet_invoice_verify_ret (104) -> wallet_invoice_verify_ret (105) svc changed
            db.put(Integer.valueOf(105), Integer.valueOf(106)); // ! wallet_payment_verify (105) -> wallet_payment_verify (106) svc changed
            db.put(Integer.valueOf(106), Integer.valueOf(107)); // ! wallet_payment_verify_ret (106) -> wallet_payment_verify_ret (107) svc changed
            db.put(Integer.valueOf(107), Integer.valueOf(108)); // ! wallet_tx_pay (107) -> wallet_tx_pay (108) svc changed
            db.put(Integer.valueOf(108), Integer.valueOf(109)); // ! wallet_tx_pay_ret (108) -> wallet_tx_pay_ret (109) svc changed
            db.put(Integer.valueOf(109), Integer.valueOf(110)); // ! wallet_tx_new (109) -> wallet_tx_new (110) svc changed
            db.put(Integer.valueOf(110), Integer.valueOf(111)); // ! wallet_tx_new_ret (110) -> wallet_tx_new_ret (111) svc changed
            db.put(Integer.valueOf(111), Integer.valueOf(112)); // ! wallet_tx_add_section (111) -> wallet_tx_add_section (112) svc changed
            db.put(Integer.valueOf(112), Integer.valueOf(113)); // ! wallet_tx_add_section_ret (112) -> wallet_tx_add_section_ret (113) svc changed
            db.put(Integer.valueOf(113), Integer.valueOf(114)); // ! wallet_tx_add_input (113) -> wallet_tx_add_input (114) svc changed
            db.put(Integer.valueOf(114), Integer.valueOf(115)); // ! wallet_tx_add_input_ret (114) -> wallet_tx_add_input_ret (115) svc changed
            db.put(Integer.valueOf(115), Integer.valueOf(116)); // ! wallet_tx_add_output (115) -> wallet_tx_add_output (116) svc changed
            db.put(Integer.valueOf(116), Integer.valueOf(117)); // ! wallet_tx_add_output_ret (116) -> wallet_tx_add_output_ret (117) svc changed
            db.put(Integer.valueOf(117), Integer.valueOf(118)); // ! wallet_tx_sign (117) -> wallet_tx_sign (118) svc changed
            db.put(Integer.valueOf(118), Integer.valueOf(119)); // ! wallet_tx_sign_ret (118) -> wallet_tx_sign_ret (119) svc changed
            db.put(Integer.valueOf(119), Integer.valueOf(120)); // ! wallet_tx_send (119) -> wallet_tx_send (120) svc changed
            db.put(Integer.valueOf(120), Integer.valueOf(121)); // ! wallet_tx_send_ret (120) -> wallet_tx_send_ret (121) svc changed
            db.put(Integer.valueOf(121), Integer.valueOf(122)); // ! wallet_tx_decode (121) -> wallet_tx_decode (122) svc changed
            db.put(Integer.valueOf(122), Integer.valueOf(123)); // ! wallet_tx_decode_ret (122) -> wallet_tx_decode_ret (123) svc changed
            db.put(Integer.valueOf(123), Integer.valueOf(124)); // ! wallet_tx_check (123) -> wallet_tx_check (124) svc changed
            db.put(Integer.valueOf(124), Integer.valueOf(125)); // ! wallet_tx_check_ret (124) -> wallet_tx_check_ret (125) svc changed
            db.put(Integer.valueOf(125), Integer.valueOf(126)); // ! wallet_set_supply (125) -> wallet_set_supply (126) svc changed
            db.put(Integer.valueOf(126), Integer.valueOf(127)); // ! wallet_set_supply_ret (126) -> wallet_set_supply_ret (127) svc changed
            db.put(Integer.valueOf(127), Integer.valueOf(128)); // ! wallet_store_kv (127) -> wallet_store_kv (128) svc changed
            db.put(Integer.valueOf(128), Integer.valueOf(129)); // ! wallet_store_kv_ret (128) -> wallet_store_kv_ret (129) svc changed
            db.put(Integer.valueOf(129), Integer.valueOf(130)); // ! wallet_rm_kv (129) -> wallet_rm_kv (130) svc changed
            db.put(Integer.valueOf(130), Integer.valueOf(131)); // ! wallet_rm_kv_ret (130) -> wallet_rm_kv_ret (131) svc changed
            db.put(Integer.valueOf(131), Integer.valueOf(132)); // ! wallet_store_file (131) -> wallet_store_file (132) svc changed
            db.put(Integer.valueOf(132), Integer.valueOf(133)); // ! wallet_store_file_ret (132) -> wallet_store_file_ret (133) svc changed
            db.put(Integer.valueOf(133), Integer.valueOf(134)); // ! wallet_rm_file (133) -> wallet_rm_file (134) svc changed
            db.put(Integer.valueOf(134), Integer.valueOf(135)); // ! wallet_rm_file_ret (134) -> wallet_rm_file_ret (135) svc changed
            db.put(Integer.valueOf(135), Integer.valueOf(136)); // ! wallet_search (135) -> wallet_search (136) svc changed
            db.put(Integer.valueOf(136), Integer.valueOf(137)); // ! wallet_search_ret (136) -> wallet_search_ret (137) svc changed
            db.put(Integer.valueOf(137), Integer.valueOf(138)); // ! wallet_file (137) -> wallet_file (138) svc changed
            db.put(Integer.valueOf(138), Integer.valueOf(139)); // ! wallet_file_ret (138) -> wallet_file_ret (139) svc changed
            db.put(Integer.valueOf(139), Integer.valueOf(140)); // ! wallet_exec (139) -> wallet_exec (140) svc changed
            db.put(Integer.valueOf(140), Integer.valueOf(141)); // ! wallet_get_subhome (140) -> wallet_get_subhome (141) svc changed
            db.put(Integer.valueOf(141), Integer.valueOf(142)); // ! wallet_get_subhome_ret (141) -> wallet_get_subhome_ret (142) svc changed
            db.put(Integer.valueOf(142), Integer.valueOf(143)); // ! wallet_net_info (142) -> wallet_net_info (143) svc changed
            db.put(Integer.valueOf(143), Integer.valueOf(144)); // ! wallet_net_info_ret (143) -> wallet_net_info_ret (144) svc changed
            db.put(Integer.valueOf(144), Integer.valueOf(145)); // ! wallet_compilance_report (144) -> wallet_compilance_report (145) svc changed
            db.put(Integer.valueOf(145), Integer.valueOf(146)); // ! wallet_compilance_report_ret (145) -> wallet_compilance_report_ret (146) svc changed
            db.put(Integer.valueOf(146), Integer.valueOf(147)); // ! wallet_priv_key (146) -> wallet_priv_key (147) svc changed
            db.put(Integer.valueOf(147), Integer.valueOf(148)); // ! wallet_priv_key_ret (147) -> wallet_priv_key_ret (148) svc changed
            db.put(Integer.valueOf(148), Integer.valueOf(149)); // ! wallet_pub_key (148) -> wallet_pub_key (149) svc changed
            db.put(Integer.valueOf(149), Integer.valueOf(150)); // ! wallet_pub_key_ret (149) -> wallet_pub_key_ret (150) svc changed
            db.put(Integer.valueOf(150), Integer.valueOf(151)); // ! wallet_gen_keys (150) -> wallet_gen_keys (151) svc changed
            db.put(Integer.valueOf(151), Integer.valueOf(152)); // ! wallet_gen_keys_ret (151) -> wallet_gen_keys_ret (152) svc changed
            db.put(Integer.valueOf(152), Integer.valueOf(153)); // ! wallet_sign (152) -> wallet_sign (153) svc changed
            db.put(Integer.valueOf(153), Integer.valueOf(154)); // ! wallet_sign_ret (153) -> wallet_sign_ret (154) svc changed
            db.put(Integer.valueOf(154), Integer.valueOf(155)); // ! wallet_verify (154) -> wallet_verify (155) svc changed
            db.put(Integer.valueOf(155), Integer.valueOf(156)); // ! wallet_verify_ret (155) -> wallet_verify_ret (156) svc changed
            db.put(Integer.valueOf(156), Integer.valueOf(157)); // ! wallet_encrypt (156) -> wallet_encrypt (157) svc changed
            db.put(Integer.valueOf(157), Integer.valueOf(158)); // ! wallet_encrypt_ret (157) -> wallet_encrypt_ret (158) svc changed
            db.put(Integer.valueOf(158), Integer.valueOf(159)); // ! wallet_decrypt (158) -> wallet_decrypt (159) svc changed
            db.put(Integer.valueOf(159), Integer.valueOf(160)); // ! wallet_decrypt_ret (159) -> wallet_decrypt_ret (160) svc changed
            db.put(Integer.valueOf(160), Integer.valueOf(161)); // ! wallet_patch_os (160) -> wallet_patch_os (161) svc changed
            db.put(Integer.valueOf(161), Integer.valueOf(162)); // ! wallet_patch_os_ret (161) -> wallet_patch_os_ret (162) svc changed
            db.put(Integer.valueOf(162), Integer.valueOf(163)); // ! wallet_list_protocols (162) -> wallet_list_protocols (163) svc changed
            db.put(Integer.valueOf(163), Integer.valueOf(164)); // ! wallet_list_protocols_ret (163) -> wallet_list_protocols_ret (164) svc changed
            db.put(Integer.valueOf(164), Integer.valueOf(165)); // ! wallet_trade (164) -> wallet_trade (165) svc changed
            db.put(Integer.valueOf(165), Integer.valueOf(166)); // ! wallet_trade_ret (165) -> wallet_trade_ret (166) svc changed
            db.put(Integer.valueOf(166), Integer.valueOf(167)); // ! wallet_list_trades (166) -> wallet_list_trades (167) svc changed
            db.put(Integer.valueOf(167), Integer.valueOf(168)); // ! wallet_list_trades_ret (167) -> wallet_list_trades_ret (168) svc changed
            db.put(Integer.valueOf(168), Integer.valueOf(169)); // ! wallet_kill_trade (168) -> wallet_kill_trade (169) svc changed
            db.put(Integer.valueOf(169), Integer.valueOf(170)); // ! wallet_kill_trade_ret (169) -> wallet_kill_trade_ret (170) svc changed
            db.put(Integer.valueOf(170), Integer.valueOf(171)); // ! wallet_exec_trade (170) -> wallet_exec_trade (171) svc changed
            db.put(Integer.valueOf(171), Integer.valueOf(172)); // ! wallet_qr (171) -> wallet_qr (172) svc changed
            db.put(Integer.valueOf(172), Integer.valueOf(173)); // ! wallet_qr_ret (172) -> wallet_qr_ret (173) svc changed
            db.put(Integer.valueOf(173), Integer.valueOf(174)); // ! wallet_bookmark_add (173) -> wallet_bookmark_add (174) svc changed
            db.put(Integer.valueOf(174), Integer.valueOf(175)); // ! wallet_bookmark_add_ret (174) -> wallet_bookmark_add_ret (175) svc changed
            db.put(Integer.valueOf(175), Integer.valueOf(176)); // ! wallet_bookmark_delete (175) -> wallet_bookmark_delete (176) svc changed
            db.put(Integer.valueOf(176), Integer.valueOf(177)); // ! wallet_bookmark_delete_ret (176) -> wallet_bookmark_delete_ret (177) svc changed
            db.put(Integer.valueOf(177), Integer.valueOf(178)); // ! wallet_bookmark_list (177) -> wallet_bookmark_list (178) svc changed
            db.put(Integer.valueOf(178), Integer.valueOf(179)); // ! wallet_bookmark_list_ret (178) -> wallet_bookmark_list_ret (179) svc changed
            db.put(Integer.valueOf(179), Integer.valueOf(180)); // ! wallet_timeseries_list (179) -> wallet_timeseries_list (180) svc changed
            db.put(Integer.valueOf(180), Integer.valueOf(181)); // ! wallet_timeseries_list_ret (180) -> wallet_timeseries_list_ret (181) svc changed
            db.put(Integer.valueOf(181), Integer.valueOf(182)); // ! wallet_timeseries_show (181) -> wallet_timeseries_show (182) svc changed
            db.put(Integer.valueOf(182), Integer.valueOf(183)); // ! wallet_timeseries_show_ret (182) -> wallet_timeseries_show_ret (183) svc changed
            db.put(Integer.valueOf(183), Integer.valueOf(184)); // ! wallet_timeseries_new (183) -> wallet_timeseries_new (184) svc changed
            db.put(Integer.valueOf(184), Integer.valueOf(185)); // ! wallet_timeseries_new_ret (184) -> wallet_timeseries_new_ret (185) svc changed
            db.put(Integer.valueOf(185), Integer.valueOf(186)); // ! wallet_timeseries_add (185) -> wallet_timeseries_add (186) svc changed
            db.put(Integer.valueOf(186), Integer.valueOf(187)); // ! wallet_timeseries_add_ret (186) -> wallet_timeseries_add_ret (187) svc changed
            //-/----------------------------------------------------------___end___------generated by configure, do not edit.
        }
   }

    public void from_prev(svc_t svc) {
        Integer i = db01.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    public void to_prev(svc_t svc) {
        Integer i = db10.get(svc.value);
        if (i == null) {
            return;
        }
        svc.value = i.intValue();
    }

    HashMap<Integer, Integer> db01 = new HashMap<Integer, Integer>();
    HashMap<Integer, Integer> db10 = new HashMap<Integer, Integer>();

}

