#!/bin/bash
#===-                           P L E B B L E
#===-                         https://plebble.us
#===-
#===-              Copyright (C) 2017-2022 root1m3@plebble.us
#===-
#===-                      GNU GENERAL PUBLIC LICENSE
#===-                       Version 3, 29 June 2007
#===-
#===-    This program is free software: you can redistribute it and/or modify
#===-    it under the terms of the GPLv3 License as published by the Free
#===-    Software Foundation.
#===-
#===-    This program is distributed in the hope that it will be useful,
#===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
#===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#===-
#===-    You should have received a copy of the General Public License
#===-    along with this program, see LICENCE file.
#===-    see https://www.gnu.org/licenses
#===-
#===----------------------------------------------------------------------------
#===-

#---------------------------- OS detection
let freebsd=0
unm=`uname`
if [[ "_$unm" == "_FreeBSD" ]]; then
    let freebsd=1
    #echo "running on FreeBSD"
else
    if [[ "_$unm" != "_Linux" ]]; then
        >&2 echo "KO 78699 $unm not supported"
        exit 1
    fi
    #echo "running on Linux"
fi
#-/-------------------------- OS detection

#---------------------------- arch, jobs
let jobs=0
arch=""
if [[ $freebsd -eq 1 ]]; then
    sysctl hw.model hw.machine hw.ncpu
    let jobs=`sysctl hw.ncpu | awk '{ print $2 }'`
    arch=`uname -p`
else
    let jobs=`cat /proc/cpuinfo | grep "^processor" | wc -l`
    arch=`uname -m`
fi
if [[ $jobs -gt 1 ]]; then
    let jobs=`echo "$jobs-1" | bc`
fi
#echo "jobs0=$jobs"
#-/-------------------------- arch, jobs

make="make"
if [[ $freebsd -eq 1 ]]; then
    make="gmake"
fi

function freebsd_sedi {
    sed -i .bak "$1" "$2"
    if [[ $? -ne 0 ]]; then
	    >&2 echo "sed -i .bak \"$1\" \"$2\""
	    >&2 echo "KO 77886 sed failed"
        exit 1
    fi
}

function sedi { #sed -i "s/^str29=.*//" res/strings/${strset}.ovr
#echo "sedi: $1 $2"
    if [[ ! -f $2 ]]; then
        >&2 pwd
        >&2 echo "KO 68851 sedi. file not found. >>>$2<<<"
        exit 1
    fi

    if [[ $freebsd -eq 1 ]]; then
        freebsd_sedi "$1" "$2"
        return
    fi
    sed -i "$1" "$2"
    if [[ $? -ne 0 ]]; then
        >&2 pwd
        >&2 echo "KO 68852 sedi fail. >>>$1<<< >>>$2<<<"
        exit 1
    fi
}

function write_systemctl {
    cmd="$1"
    svc="$2"
    if [[ $freebsd -eq 0 ]]; then
        echo "systemctl $cmd $svc"
    elif [[ $freebsd -eq 1 ]]; then
        echo "service $svc $cmd"
    fi
}

